apiVersion: ENC[AES256_GCM,data:SiM=,iv:lNijRyz8lebG/mmWUrbwzKzLocaaaIHqSSequoln3zs=,tag:E7Jv1J+dUmFxbW3C/0vL7A==,type:str]
kind: ENC[AES256_GCM,data:C8qwE4Rx,iv:YdZCtTWQXAfgiqPDhS+QPrhcm7XfCRN7HH3e2XaQTv0=,tag:9zIZ4JrpgjxGV1c5MBApKA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:PE+yCuHfBpcukBtAecq+qt3QRCUfY8Gq,iv:2aQuvA1P0cB2u47p2eKi5HzQGwultdFn4u8HoALQpeg=,tag:tLX5PZF0ckkZkLph0xtIZA==,type:str]
    namespace: ENC[AES256_GCM,data:84hwhq8=,iv:t2/EgCHRBOcPEcrX6IrcuEuTA3lo71KKvhQfb2RzRLg=,tag:PAdesEMfd/IlESQlhbjutw==,type:str]
type: ENC[AES256_GCM,data:Y28tkVFJ,iv:uOUnexvN3UN/n8x59fjc6jo79RcTWx7/O8b4elwITGM=,tag:rDOBLDF0QahIEPJv3anJAw==,type:str]
stringData:
    applicationId: ENC[AES256_GCM,data:8IiUdCchSWjTXg0Dhluh7cUXAg==,iv:bYLF0PMNyHB3bx4qVXUlBNBCWXMd+7ENu11mXiuTj+Y=,tag:XKSpYTLMF4+YImM0a6Kjgw==,type:str]
    token: ENC[AES256_GCM,data:Z0QtXm5edTI9rwrZzmBMbu0j2LUDwMUU3gvLD2enmUqPGa/YilffpIy4wnFvRv4RNgilEoeOAkb7u2OiYz5e6iuwa6CUS+Vx,iv:8pkoMYIwzbj5FcWkNuhsZgf7SnLov/acjet77TCaI34=,tag:hjJ0skIS8yFPT1GR3XbeDQ==,type:str]
    publicKey: ENC[AES256_GCM,data:ZMupK/FSUtKjTgc/Y+PGQvuD/bRJUmiGu0fMFoSRrERWITLJDudUvGGLtIWZoXJBu9+LAF1MjcayAXWEdIAP0Q==,iv:js33SxU/cMq2tRHO+f7Zd7cytyG/RdVdOqYRTbyes8E=,tag:euleLOin8Z+AuxmjwJecqw==,type:str]
sops:
    age:
        - recipient: age1svstfr65yepsdhxu3kxdy6t02gf6l779qxsqvd0dv2r0aqgzcpyqkwvl0c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJQlZLRXd1cWdTenBCcWk5
            RFJuUnl2TkJKWjlXd08yRG4vcGRDa3VQU2drCnhaNFJtWVFuRjRvQWxybDh1QmpU
            SHNTNDhtS0NuUVczRTlob3c5dWsvOXMKLS0tIDZDZFRGK09tMXhxMzZVVnFXUmhz
            SnhENUw3SXowTDhHbWhZbk5NVHVHV3cKU6+gALSfiARQ77vHPRa9aiJ3x7jKTT5o
            2m7UURGDOW+xbKgMT4PIAD5ZBRnWo6+Fx5c5nyBxQNj0T1s2ArzCSA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-12T10:05:56Z"
    mac: ENC[AES256_GCM,data:9e6InhSoPXv7gitXUCxRMGGwTrSZg8N4yJtcAtJEkHIDbF/qaYXWixRV3N2jRIYiKECZx0PTg6Iwrf9DiK8H6hYOYYB3pol6Zl2cJOeBpBZ+i6GXOKmrpsJa6JHo+dTL93GXwR0tBCkJD+31ADBKwGpHVZBeLkXIme4HXcUXCEE=,iv:N7AFxYChyzi7rQsRGdu56krcZeE7jAyL7soV/4GczvQ=,tag:i722XvLH3t7tv5DYIL6xGA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
