apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - rustfs-console-login-secret.yaml
  - rustfs-login-secret.yaml
  - rustfs-volumes.yaml
  - rustfs-helm-release.yaml
