apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rustfs-logs-pvc
  namespace: rustfs
  annotations:
    recurring-job-group.longhorn.io/default: enabled
spec:
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rustfs-data-pvc
  namespace: rustfs
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  resources:
    requests:
      storage: 1Ti