apiVersion: ENC[AES256_GCM,data:8q0=,iv:Uz2e9lEbBy6HjhP9LLIdjEsZpAOQXfETAhSCy0YCBg8=,tag:evIEXeXIMgG51x7ST728KQ==,type:str]
kind: ENC[AES256_GCM,data:gNF0xtcf,iv:D5WRrWdMzOtkWLDyx7swk+2UCJ2Gw4KweCrqSy0ubgs=,tag:hYATQEDTl+by+3FmbAIK4w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:omKwhW5mcaF8U+tv7JENshmmBknn2WhqcaHZ,iv:XbHbK9QIPkv2e7285JoLBd3sYhFFtv6bOL4pcBlQQEo=,tag:J3dH1T0m0JLnf6exd3dwIQ==,type:str]
    namespace: ENC[AES256_GCM,data:wS8q5u5k,iv:8I/TWjMw3L7S9F05hLEtHV8zpV1Zqv54B2/fbCIImhw=,tag:cyl9ROloPaB350XrB5IWhQ==,type:str]
type: ENC[AES256_GCM,data:EB4ry2a9,iv:nX3Mwy/nezeiNkZi2To47sKHOTSbrjT+MuttCcxTsgY=,tag:nvhR/JdYgj5Gm1mJTkmkPw==,type:str]
data:
    RUSTFS_ACCESS_KEY: ENC[AES256_GCM,data:4nYMd0c=,iv:P6C3G40BHNrayhMRnGoFT0MX9qISYrFgmB7rBpxx5eU=,tag:UqpSobanCUd2GXX4c+S7ZQ==,type:str]
    RUSTFS_SECRET_KEY: ENC[AES256_GCM,data:zlRng/km/i4=,iv:GORLbXqbzYFMStUuDNQV1uTHJxLd2sG/CG2dGS0OWFY=,tag:zIRtSibP13v4dGl5wXrRcg==,type:str]
sops:
    age:
        - recipient: age1svstfr65yepsdhxu3kxdy6t02gf6l779qxsqvd0dv2r0aqgzcpyqkwvl0c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiODFlMGVLbE1PcWFuVWdz
            MnZVLzBReDFXMzhLWU13UDd3TTJ4TnRwQ0V3CnpTcFlVNG1EZUlkcXJmaXpYYks4
            K3RTckl4Y29QSXp6cTFHZ2wrTmg2RU0KLS0tIFNCZC9FYXJLOG5WYUNLS2MzYUVI
            c3ZDUUp0QWp6WVduZE5yeW1Mem1xOTAKlJaWAYkJyhZCXcPPab6RtYp369wQI0DA
            hKLrC4qkiI6sP5s0Gw5DWByf9JUKBPJO2M43xeKg2kG0hDoQldwhzg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-17T15:57:04Z"
    mac: ENC[AES256_GCM,data:vmstWXcIGIKq17vI7xJyD1tpdwgqIhvV8g54H51IEu6DLbtgRdTha8aG0NPRGrW69cg7x/+J7AiUHmgeYY1JtW559htnraosQfxd+VcFeNT357f9NN8CqXVebYD6Zjq3e19/rfa49LUNlBFGuaDGJ5kXrbnnNK3lqNM8e9VI2tg=,iv:I3o+0MONYB4gzWjuIu468wszkimrC1NhTOcNSV2cMiY=,tag:RmOghLWRD09V0uUSlLSZPQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
