apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rustfs
  namespace: rustfs
spec:
  interval: 5m0s
  chart:
    spec:
      chart: rustfs
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: rustfs
        namespace: flux-system
      interval: 5m0s
  values:
    mode:
      standalone:
        enabled: true
        existingClaim:
          dataClaim: rustfs-data-pvc
          logsClaim: rustfs-logs-pvc
      distributed:
        enabled: false
    ingress:
      enabled: true
      className: traefik
      hosts:
        - host: dashboard.private.superkooka.com
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        enabled: true
        existingSecret:
          enabled: true
          name: rustfs-tls
      customAnnotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: "true"
        traefik.ingress.kubernetes.io/router.middlewares: rustfs-basic-auth@kubernetescrd,rustfs-redirect-noslash@kubernetescrd,rustfs-replacepath-rustfs-ui@kubernetescrd
