apiVersion: ENC[AES256_GCM,data:otY=,iv:WjwD54BFTgPiUSBJVOU3eDyHyIOyXA/NLd4swn+wSeY=,tag:IL8grKAGvDmqHtI3e6BokA==,type:str]
kind: ENC[AES256_GCM,data:0zlbbIb2,iv:wMVrfa9C5igN98H/2m8NPNpUKNmsz1STq2EWavcjbrM=,tag:ImRv5vlNWpkphz2qoek4pw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:Wud87UX0JSqA4VBiCcQNxw4=,iv:C7kCYowOl4LHZrjUStIfu65RN7DMD9eSkZfkjcD7qbE=,tag:pqRPdQHJz2g2OZLM84WCJw==,type:str]
    namespace: ENC[AES256_GCM,data:o/Uh44VY,iv:7fxCw7QPfqM13YKPf2EU+iem2SCnIjsUXm9zBIwYc8Q=,tag:CBtJQsoDXBtpkdQDNcOTIA==,type:str]
type: ENC[AES256_GCM,data:QI8Fca0p,iv:rU4alfwhIn0ZGQGLLgYRqRA7NMEfWuzpCNzcSGLsC4w=,tag:JX/BcADjc0qlm6egkSILlg==,type:str]
data:
    users: ENC[AES256_GCM,data:RwaCo1d7zZAplTz0w8JUfrlLkfOsEDo+zikoH2b7afx0paode9bnJ0W+3XV3sjUbsgX4tBu5IP5WC6Mb,iv:liT/tj4Tthpr4TDnGxjotW65FuTwUHkfkA3EjoHtfvA=,tag:68oigNn5DE2YOJjQpq6pZg==,type:str]
sops:
    age:
        - recipient: age1svstfr65yepsdhxu3kxdy6t02gf6l779qxsqvd0dv2r0aqgzcpyqkwvl0c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIK25PdGM3ODRXYUxLR2s1
            M01QaGNUZWFHNi9IbHVRUGxORytMYW1UZ1MwCjA4eEhza1pHa1R1eGN6a0dmRm5a
            UHAzOHpyMXh6a1d3QTFUMnFCNFZQbDAKLS0tIEhlRkdqSTZQdTFxNWNabEVLV0t4
            dGRZQlE0MW5sT0xUbEZtL3ZnbDR4bXMKOal2W514Mw293+6xQIjULNc91L/SUir8
            LRCzRNukt4z4SLMyBEqsjZYnia99JEOAnt79eRJ6vP27DgqdjoOlhQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-17T15:17:07Z"
    mac: ENC[AES256_GCM,data:DNH+RNCn/TjE7+X96Rto+wnT9YVHsVL8qXGwA5FOUbQVNUX3Qjmcz09X5GajO78x2jm4d+FzdTZBbMcHVgbYi1pEPqNXuida3S2nrWvN4m11RG9oZ+c6lak4G8K9i2rZCevpVJ2KJ9dc1RyItom/uGg/SQMqaz02jy6wjhAdEPU=,iv:vjOIlqYxgD9CeY/UrTA4bzHORBZIkSn0JYtFLJ83LzQ=,tag:IbqtWXTaefktWWtXZWQ30A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
