apiVersion: ENC[AES256_GCM,data:hOE=,iv:r4ijmIcTJL6ElqAfd1d7+YDgggz4WU6cP9IIenTTyh8=,tag:u4+texKvhCiMM+an7QbGaw==,type:str]
kind: ENC[AES256_GCM,data:b0H5uUnX,iv:qfnHNgu6P1z1B1uW8sFKrdw7dbassU71fRwefaW7zlM=,tag:E3FiHqyx5IeQ6MQ7y64qng==,type:str]
metadata:
    name: ENC[AES256_GCM,data:Rdkhvr575aODjEfJeTuwOEGJ4T2AU65GTJkT,iv:PbCn53ugCUXaYCOgHsl0WB5ufK//chqEfOfkbxreczw=,tag:hXeWAtji6B/OqBYqSTZt3g==,type:str]
    namespace: ENC[AES256_GCM,data:/4qfozoM,iv:j4+X/RKvatQm+7ex9ZXY64yC8oa3ZOA3l8lzWxKn2lU=,tag:P5hPIAJ2zMKrmi1b6siFXA==,type:str]
type: ENC[AES256_GCM,data:tEV8XKbS,iv:HsOupKP2tynIGBC6eNsD0XNUVC0o7kp+HWCmAbt30Zo=,tag:2AmZjLmLmtmZfmj1/1qiiw==,type:str]
data:
    RUSTFS_ACCESS_KEY: ENC[AES256_GCM,data:A7scKw8=,iv:NO9AAtAUYuqkrwbwFhKOU7XrCxLeYOkgPcgLw/OZheQ=,tag:44RWNRPDDqdml5X0VZcuWQ==,type:str]
    RUSTFS_SECRET_KEY: ENC[AES256_GCM,data:sNDGtZVn0OE=,iv:y6VX4l+yT6oLxdBfVUMiTCsGbUihsdMgvBnSwmi61+0=,tag:h+3X3MTbRMpDYyiv8NYpVw==,type:str]
sops:
    age:
        - recipient: age1svstfr65yepsdhxu3kxdy6t02gf6l779qxsqvd0dv2r0aqgzcpyqkwvl0c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1TkQzNDhkTVlyeXZQZVE3
            aXowRTltNlNSNzk5Wm91Z28xT1FuRnhSVWkwCm9jYi8renVHbE4rMEdrbGdUbnBE
            Zkh3TGw4SThJb2hNZjBudmt1NURDb2sKLS0tIGJZdDBFQmtyVzlTWUROUk9tSjFj
            M0oyaUdtc3F1eHdGN2VSZDBHQkUzVzQKitrh4cGBZI5NDN+4+eiOaPcF5nJZJGPi
            /xrQpZMCza1dTiahkJNgxF0co8tK7iCZq8ge3dkMAXLvgaKrTS9euQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-17T15:46:19Z"
    mac: ENC[AES256_GCM,data:tnP9ygpms3KAQqf6WP3rGQOwe2F4BS+KH6CV79rPr1e7u8qau2NDRXUuatqjEMtYldLqzu+DFYLsIQ2APK0/WgXPYHu2wcFQ4WlU7QehxY4xCumPLmqbt1qrjFDBjE5zCnpIY4Xa0ghgJ4DYxE2u86n3ytIaZnrB8nx7O6t0t5s=,iv:UDh4+y0JwcFDK66Xn2r5OvLmXgzrVQCoiDfac2eaE+U=,tag:lNWNeFVR2TbraskBrB9UnQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
