apiVersion: ENC[AES256_GCM,data:kZs=,iv:q73C1oLKCppIEmdPuxq8wSPHg1ozCwRKtCJjPeL1KEk=,tag:IpuW4uyJMLebqOgnnE1mzA==,type:str]
kind: ENC[AES256_GCM,data:AgQopEby,iv:W0RTPITMzhGu846rRdpnBsBlHsBf5d1rAv9BaH0q3tU=,tag:un8sDcrUWTa4o+TcO+ykHA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:fPIJUWCQFCp+X18ihKsvWCxe0RD0/9TDfleM,iv:dZbAn0YNP9Vch5c10UG1Vbda3l7fLn+JSdIt4fiFEkE=,tag:asAxJJC+MtGPupIGzSLFVQ==,type:str]
    namespace: ENC[AES256_GCM,data:qIyghm8C,iv:8DYUA+KoBwfe7pPmh6JM47yeIaPBY7Vqhkoc4uzQ7ik=,tag:4UaapFKGbMJM64DQ1IBUEA==,type:str]
type: ENC[AES256_GCM,data:RQFaz7pT,iv:Rb2EopC89ltWQobJT79UmSaa3r6OsxZrxbC77Qn0QDA=,tag:CT7hBsVkJfS3+edowLgVuA==,type:str]
data:
    RUSTFS_ACCESS_KEY: ENC[AES256_GCM,data:UI8UEom3fYs=,iv:czY5xHNUQAk790AJG6kM6kSaAqmhip0rf9xapLmkNfo=,tag:d1dyeJEvWlcBLkaUKo/+iA==,type:str]
    RUSTFS_SECRET_KEY: ENC[AES256_GCM,data:WI04nlJ/UGomE7Tw,iv:1sWigWyG5bX/kpCP8KIWtcSmL7xwxhJfj77bxWwXg9o=,tag:QPonLozcHzknFp92IuE37w==,type:str]
sops:
    age:
        - recipient: age1svstfr65yepsdhxu3kxdy6t02gf6l779qxsqvd0dv2r0aqgzcpyqkwvl0c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIcTJaT3V3UTNvdTN1MWIv
            SjBYMVllT3hXdUZPS2c0NDVmM0FkcEU1MmxBCjZ4ZVZzSWYzaUszRXBmTkJYZStW
            OTBoRWUvcXFULzR4UHlWaG1ia3hQcm8KLS0tIEgxMVYrSEhKZTh3dHY2U2I5dm9T
            ZmtxYTBzSGtqakloR2o5ZkxiTWJDeEUKBpGmM7e72N6vv8WhkycwlqktCyt4LcG4
            sxfMHUN8hBRF5GIdwvmwjp8keLrwkoXrVhR7ukQwKW/6cHzWYXwkDg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-17T16:02:55Z"
    mac: ENC[AES256_GCM,data:7/gg3k+KP+79CUZX3BvdBdNZgCpNQ+ysE48pXqvC9pJBSYj11iydE34kBTfERqfxN52xFtPL9sOPSNDzLNNonA8mCRfVYxsEaXjaJYmhD9nf6fJeA5XKaRmXnIjNjXkadTw+UJxUDjxczrhNZwZsokoTmyrAaT5ODnh62XOqbOY=,iv:5I3ZztfLT/LDzsBhp0jRBcpeEaZql2TaBPgPUYBJ6rI=,tag:dFzub4mqOwCFOw+3wlt4/w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
