apiVersion: v1
kind: Service
metadata:
  name: fivem-prod-service
  namespace: game
spec:
  selector:
    app: fivem-prod
  ports:
    - name: game-tcp
      port: 30120
      targetPort: 30120
      protocol: TCP
    - name: game-udp
      port: 30120
      targetPort: 30120
      protocol: UDP
    - name: txadmin
      port: 80
      targetPort: 40120
      protocol: TCP
