apiVersion: ENC[AES256_GCM,data:ic4=,iv:NMU8/n5nmkLW8S0hXn1MCBrvf1h+jwcsI2EdXHuWPaA=,tag:v3CRCn0JLkjF0OIaY+bMWw==,type:str]
kind: ENC[AES256_GCM,data:ijcyjx+7,iv:GhOJOA4L+3KLsj3XE1WoXy3+GBi3NhtGQFuE3PmzHww=,tag:o6CP6nplDqP3Zg/whsSEgA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:VOW/jAJVyrv0ug==,iv:LoTd7ACfYRYTaUHOPb7KXrIeJCkjWPWdpB4PgmrWETM=,tag:iTCFw2tGO62aPoChl/WE5w==,type:str]
    namespace: ENC[AES256_GCM,data:fM73nQ==,iv:K9hXt7nhnjn+fVCUc59kCwQrjMWIPfm/uqDdjLcqggc=,tag:wH96GQYEnQ+q3rdNGipk8Q==,type:str]
type: ENC[AES256_GCM,data:j+RdV0b1,iv:r5ZXnUT8gZP/yFAWJg799+Ry374Q+udOr3JFbcCCPhA=,tag:YeEz4LuSJotJuxbCjbMRiQ==,type:str]
stringData:
    server-id: ENC[AES256_GCM,data:prqI712PUg==,iv:kxBn3/knQOxk7mdupFMT1WRVqqQJ7PhLOypMz8qjgxc=,tag:/z1RdTNly3f6QWiBOCQjVg==,type:str]
    license-key: ENC[AES256_GCM,data:DY5AQvZfA8kiJ/t//iOcfj+M/A3BC531C+cDZMILpr0=,iv:Oxg2ZBBZoWf2HAYfEv/B4WAXyIFc30WlYlNcvtEbmtg=,tag:ufd339LLzA3ZwhLsDNb/FA==,type:str]
    db-password: ENC[AES256_GCM,data:X1+e/EtZBGlKwnVdkp2bAaWfL4EaVa2DYWaDbcFEwkor0zlby3JVp3YIb69vAyKM99kE6f+fsKkWzflWceqqcg==,iv:6ZKkgMpFjKp0IebyeLLQCTZ+BS2HCqVH0UZTmEXYgj4=,tag:Ivt0YGVrRq1o9SBdhaq9MA==,type:str]
    root-password: ENC[AES256_GCM,data:ci9aZSfVs6EHtXEb+gYIUjwNnNkLdVps4VmXYGtz0zBQ9/TBc/0m3rLlSdgO0WvaQijG0l1dfZ7BMpkZdUF2CA==,iv:TUJJoDZh4qGrQmTkdmKfya+1G6n0rEB6UXTF4Y8YSx8=,tag:Ii+TDsmA0riYgi6w5kFxGw==,type:str]
sops:
    age:
        - recipient: age1svstfr65yepsdhxu3kxdy6t02gf6l779qxsqvd0dv2r0aqgzcpyqkwvl0c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtUkRXY3I1cklaNEFTOTA0
            ZEJJcnEvYm1XdHZYSUhVK01KS3piTUM0NXg4Cm5hK2pMU1NjZlBtSGFGSUpxQnY3
            WGtpWVc2ZzdHKzhsb2lHd0kzVEhKNm8KLS0tIEFBVVF3U2VlN3lySm1xYXJTbzli
            dHF1RTJrRTlGcndmL0hBODJTWkhjN3cKXOC/huv31Nu8yjm++fn/pl2hXWbv12GV
            VrmUFxq64q5phoabGcChAeCeNBT4ZpqeJ01ufl5YrlygVgV5MOJjjw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-15T20:58:53Z"
    mac: ENC[AES256_GCM,data:b6azUJnkfMtH2peRBeKKYNq1b3OtOuYb8LmDKoMNoydo70ptLIv2pLFggJOZoGnfeBJuk8Ydit/1UPgjH3kgpqhEfuwCXYTGY6cmDa/eH1VdBTxxQed/Qf3ODi8JWPW8lcvvSx34EawOJ6q+QKnp6JxjhED1KXtCxirsdYrMu9k=,iv:xeufJ6G6NQ5SU+d48jgMKfxwCr+fYJV7tWc6GMCiBn0=,tag:LaASdQIYSmMRJZ6QU6Qfqg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
