apiVersion: ENC[AES256_GCM,data:Hnc=,iv:5rvoNZfJMopBD1A3iWaVYoBZTZjnPCUtl/0CWy2A7+0=,tag:kKvMWmzeAlzYPer3P/RiLQ==,type:str]
kind: ENC[AES256_GCM,data:N8DcIQEC,iv:v+aNMvN8GYFTMQsYBko67qW9C0yc02erqlZk0NHrEno=,tag:/rLHqdPbocIC/kMxBZthEQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:ngrmYIy9XtMJXQ==,iv:YpsCDNC8SAAyTbsSyZZL1p8cu9HaWYxhmykJ19DYu84=,tag:k/Ccgw9Nl+9EgpQifbndkQ==,type:str]
    namespace: ENC[AES256_GCM,data:DVh/WQ==,iv:ucM62cpt5hgYko+chFA90kbbRjf2IJfpMtEf8B1+qMo=,tag:WVHJbKKzELBNOKIjQjdt8Q==,type:str]
type: ENC[AES256_GCM,data:auZYldEb,iv:8fj63JLj+PTN8s4BqjbYfxnjo5hg1yVuIiFEHVrv4Mc=,tag:3JWUSL11Rl8t+KtKcApB9g==,type:str]
stringData:
    server-id: ENC[AES256_GCM,data:u9J8BZMk6Q==,iv:eyC/14dwCXKzlAT5b/3pWHO3J8za3ZtvVjTDEkz4L/c=,tag:rvnUx+Hxe19ehtuvz6c+sQ==,type:str]
    license-key: ENC[AES256_GCM,data:aFdWFZmD2v8OG2/jkVO4qNCZtyyn+sjdLX0NajRwoxg=,iv:8ltRInL3R26t38dXDQ+JyFQ2esugPLXdZ1m7iyelKj4=,tag:SVfNx4aL+iVFC0szCx4m9A==,type:str]
sops:
    age:
        - recipient: age1svstfr65yepsdhxu3kxdy6t02gf6l779qxsqvd0dv2r0aqgzcpyqkwvl0c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQdXlIa2d5S0d5TTVNaFlp
            MmRuV2JKVlIzckVaSEhZOWZzbXppbVZiK2lVClFNblRBQzhzU214aWNOL0xPV3ZT
            U3BZUEZnWFdrM0RqTzdrRjZMWldwUmcKLS0tIGsrem9zUWJDVVpnRm1kbUZjeUwy
            WDEwTlNjSkFQRUV2RmtCWTdBZDEvVlEK7gvkrq2+hwhgovJfCS80G9JHugvN9Byp
            tCtlO4JcDuSrzFltBAsc91uViZwCGUQrqKlGHprsOAnXlnxBk9kBkA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-15T18:56:14Z"
    mac: ENC[AES256_GCM,data:yxiyH2UJL9oy/b1+fe2YQwY4t5H5vj0s9dYlSwywdVArc7JpvoY+myQa4YBHG49avorHihyJeoH24lrNwWJFbQIVfhtmYo1it4JsJ4dKH/v6ZJxkNK79MNjlN27AhB0sb/0znjgDSlxaRyJAarh6moa8/cyYkG1bvYTNlb33n2g=,iv:Qvrt9pdSUU/yKsrlwh20fONF/CL70tSfUf4gZMWZjG4=,tag:18hjhwJXol/QSJGuQT0Blw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
