# Jellyfin
# Pterodactyl Panel
# Gitea
# Wings?

apiVersion: apps/v1
kind: Deployment
metadata:
  name: socat-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: socat-proxy
  template:
    metadata:
      labels:
        app: socat-proxy
    spec:
      containers:
        - name: socat
          image: alpine/socat
          args: ["TCP-LISTEN:8080,fork,reuseaddr", "TCP:192.168.0.11:3001"]
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: socat-proxy
spec:
  selector:
    app: socat-proxy
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: gitea
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`gitea.superkooka.com`)
      kind: Rule
      services:
        - name: socat-proxy
          port: 80
  tls:
    certResolver: letsencrypt