# TODO: chiffrer avec `sops -e -i apps/home/game/ts3server/secret.yaml` avant merge
apiVersion: v1
kind: Secret
metadata:
  name: ts3server
  namespace: game
type: Opaque
stringData:
  serveradmin-password: CHANGE_ME_SERVERADMIN_PASSWORD
