apiVersion: ENC[AES256_GCM,data:PPQ=,iv:UzvLMWECTO2+vyVV6iyyCBw//uH3w+BkLMao9Wi3NWA=,tag:R70p2YwRpyCymsrFBV0thA==,type:str]
kind: ENC[AES256_GCM,data:bn1rwV4F,iv:FeoMfS85bZyHRPGePSh8mNXaWy6LageYFybA8LHdXOc=,tag:8w5PMvdBdxJDHqjdwObhVQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:UW8kgjQSSaswKcR0xXrRtx1GgJpxkwWllg==,iv:z6hmr+E14FtkXeNwZVjvKodqlA1ImjT3LBBwnE1EW8U=,tag:FTtKzgVjzaofCHstgZIWhg==,type:str]
    namespace: ENC[AES256_GCM,data:BXGeavY=,iv:VqfwvanB9GVH1bcRWYX55iBwyZiqBxtdEj7cm3hcKRk=,tag:B8sLc25Kz7/czDVKIKs7Cw==,type:str]
type: ENC[AES256_GCM,data:DjGcDizY,iv:Hzuomfl9Vv/PR628Grq7X7jJgzDJHKkfsU62Eb5iKs8=,tag:55/waexMBmjjuSrklUgeBw==,type:str]
stringData:
    username: ENC[AES256_GCM,data:zt12Kh5gkJBpPp8q/g==,iv:xlzd8uWTjO1nryLsh3Y2HzwWvQA2mCttjs0loVTN+rM=,tag:HWuiD2UEaT9Zi6akHrYZNA==,type:str]
    email: ENC[AES256_GCM,data:+hiF0uVyiW+Q/qoynWdXRHg66uw=,iv:9T3RhQUBDt6gC1KfhWBdBTBSoewpbMjKlE+LYQvp9ms=,tag:Uk83zFaMo5Hm6z6mk0omGw==,type:str]
    password: ENC[AES256_GCM,data:NWdFHKYTxYBauL+zjshVT/YNoyc+nImtOF+l0rYnjNnpbJUWWZSNQlJPZ8W088bljArNoQjJEAxtjRiXKOKcKA==,iv:wSiC4C7C6HMb362vIl2VjLsheiut9fzQMsBv/cwSFvQ=,tag:HO8AKP6kzmhx5Uj8V5l1KA==,type:str]
sops:
    age:
        - recipient: age1svstfr65yepsdhxu3kxdy6t02gf6l779qxsqvd0dv2r0aqgzcpyqkwvl0c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3RTFPMHRnLzYyMHMxeWFk
            T1NpcVFCMmNqS1JXelkwK1F4VXhWU1V4b2tNCjNFMExaSTJOZy9rRk5kRVRuWTlJ
            VHJtWmdoYTJuYWI4VGpRUnYvTXlyMEEKLS0tIEEyUjIwMWNUTzRPNUpIMlBIazA1
            a1hYQ3pxVDFRbDgzRHp0Y3RtSlVNM1kKpzjICIrUm6jId8tS5qsZGbtqi92OTr3R
            ASd4vUVUIHnsuv8rFahTmKrTpn1SVEa7eaET3Ot6szk0c/+pSxlPdA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-30T23:06:09Z"
    mac: ENC[AES256_GCM,data:3tCwOXGMxbNKdOK0N8Cb7z7zkzTjN2RVxyzIhvFaiULKH/BmtyCMyPCRahNiCePIyAGlBWu4kaXQeNLAZb1zwqVydqNkhO59l5ZZu/sWPP3hghtlqgtQRqPesyEfTsHzSKk5nYK0sc80VzQy9wJ4eQmgMwWgK4r3piepvGghA14=,iv:6Q4b5ZtFQ7goDonaG4y+S7BWeJ9j5f37mHapa3AqW6s=,tag:mR2Xp1HyPdhnuLNhR1MBzQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
