apiVersion: ENC[AES256_GCM,data:XjY=,iv:voudbdXvpyyRGLwlA+wq2URn301UXZ+K0U1Xzmgk7R0=,tag:mxN68kHCbGs+Y7aS2mVYhQ==,type:str]
kind: ENC[AES256_GCM,data:2kdCXV9O,iv:eqhvV8BpwxBSQIyFhpN17JdmEnizHTnGuouJjCYhFj8=,tag:QNrbz0y33XygfbNL+itCBA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:nXzFQHv+QuTKuWYWzfxn,iv:lvxTYEg8YTHXKWUBpeQfVFvx1cjXUvWummiJzQnq01Y=,tag:BfuvIFp28x6z4onPHQVY3g==,type:str]
    namespace: ENC[AES256_GCM,data:s3M2MlY=,iv:fLZlalM/qDrSQkcATPQ3O/WGNw0jkIkOpwRFyrJXyAI=,tag:VMRxcOzoo/01ZIZK4EzUfQ==,type:str]
type: ENC[AES256_GCM,data:zRC86sj6,iv:xTE7rlOlkOPfiMV4q8MinZTSdbC6RliPtEJF2HzEt6M=,tag:4x6GNjqv6aHt9eTjDTdmKg==,type:str]
stringData:
    privateKey: ENC[AES256_GCM,data:slquyjY+WMwcUGpZNhODfVQJZTr4nzGGJmRgKGwOslGZb0EIdz9UzRE0tSt3LNdTWfi9A3/WrEbh46OO+VU4RY4ztGHMVXshJydYmhRbrkDjRXVJPNYByHngyj8UWFyOqEpN8c455BhGV7wlM6ZDuAy1NXxiKLZwWmR1d2Nd6HGTBFMXApGdoXGaK81KAbbIkCS2k3YUn5muXSTB77Ysj2hl8DNh/YJ8KTAKLYcZouaOYruPhHgl0ld0x8cn0UJHxmUyAqQoiioEiFtv+aP7dJUSXuE0W7TKW9joil5ME+o18BUw7EH9vHS+FGwRaBPdkFD8zGSX2njbXnPYW8ne2Pqw6nv/Z1ESbSctL9sJtOuhN5Knr9BFDTxJuhW6xDd+Qze8BD6GVyME28K6adQW+hgQlQYeOCsjSendhmiHJMbAnUvS22a7ES4vKhjEuSnqT9koLUasgnku60WlAXe+9EZ+3ERH6tyclWIaK1JptQSuU1O1NxRNSoJf2BU9AHk2tDmSTASu8ju2bXjM9uu0kOVnScU/DIWQ4FjUQ7FJcYvShYuUZIFue/zuBTLeFczI4S4IUNxnFcRZdx0Ko9T29GFFqfllviXWD5LWV/R2ZueISwKj4f/jLXnz3X1RL23fvPV5Sz+qB8/AFT20CyynqqTK7vvCqiqQRIYfxDZzRt8kFfC238rZ6XJkYmkf39ANYy9hGReVleqMX5z6fYjGLZDxc7KUpuYz2FAOoP9Xim9kkTsT2L6hK6g+70aXEjj+tASe9uYzqsxY8DWLTbnnZpTTfyh+u6hxlNDN3z5c/oVqQA8SChKz4CLORCEvqwGhTT0G4JVn+wkGV4NenuuVNJJuPkHDdBaUM/YE9PrmaWTTo8+LMX5JpVWQ6HVCjJhXVdUff+35awHqXuxK9U/lPIVScc2hFvN/1nrFyErM7AjjBJh1NkkLs6brweWEwTb9hObeBbBtBQyKWW3DMHZthSqKN67Cqzarr2gLck669j+mq8YR/IETVHHa2J1XdGiPyclncCXBCvoj9CJJgrd75al4P0nR75LwDLG8XOOPXZJOMynz2ImJy5AgdEU=,iv:Nee+8qWBKYlM9ph7kLBnm2HQ7f1ZzGp/p2+psOLPwNc=,tag:MThGOw2j8xV5+YqdBLLzNg==,type:str]
sops:
    age:
        - recipient: age1svstfr65yepsdhxu3kxdy6t02gf6l779qxsqvd0dv2r0aqgzcpyqkwvl0c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnUTIxOWh4ZjNZSGIydEtk
            cGx4NjBRUko4bnFKQ20rc3V0SHRkbEpLTkgwClN3bktnRWRFM3JOWGxvM3MrM01p
            NFVudnBNam44bnhzQ2VSZHYzdXRWNkUKLS0tIDkwWlVLZytuVVVHM0F0eW90a0Ju
            cHJaK2pWaTdnQW5Ca0tyT2prOE1iWkUKRWh5aKh0YkK0kfLtmEE5Oq2F9iMqZdqg
            +bzAGLQ3W7mnhAShEINVTenkS74JBFwNwFLqKzwMx/mE28olr/jdMQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-31T17:10:13Z"
    mac: ENC[AES256_GCM,data:tZg5xVDXFRrhJn2At9aqVBH7h+Gmu4JNDgFglupuxlqY301BFfguRoWEAJLnCZOtT4qo8NcNpkP3tZ3Rn/Rp13ckOaaTKMZ3hn+jFpKIH/3jmvGmdmB7COURts6JdpYP2e41lnln4gI2KuklqEp7qf6+kQGvdLAuoUxY3n0XElI=,iv:LpJfwC/uBXZPPUprn2xxd8P+NNss5X1fS3RftkH3ZxU=,tag:xXTlHIjCcTtS56/8JgbN4g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
