apiVersion: ENC[AES256_GCM,data:m/M=,iv:SPpvqsGgbGnkXg/Dlg3GW0yqII9D2UmmAPr6PeTgcD4=,tag:1Uff8IcyYSS6Z6Qtgy/LQA==,type:str]
kind: ENC[AES256_GCM,data:7jJlm1A5,iv:Nb2uAAvb2fnv93Mxq8wjC6bY8kTfcbVAsXdmEPLFjuc=,tag:qBbnBicw2J3RhrGzJTfjaQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:WKP2dtxmJBoGoppKYRFaaDCHQ56cqsYx,iv:5ZKNRJBJssyFt3OBDAGjcIUvdftYWIqF6cxIJJKVqsw=,tag:KCTbDZ6kf3pY1CwtOlT/sg==,type:str]
    namespace: ENC[AES256_GCM,data:xWx2PHQ=,iv:BRQcsGFRO1I7ILmWH28VtKU11taMqoI/Ug7JlLyIW34=,tag:AsBmqDOeGJKjZ+xM78Or0Q==,type:str]
type: ENC[AES256_GCM,data:WxQOkFd7,iv:9flE1W/hDOAU4G7wwOa/Chxm1Gmh4jnB3X936A1KJh4=,tag:vbJfircfQ53vciPijkmMdg==,type:str]
data:
    authorized_keys: ENC[AES256_GCM,data:kVLbbovGT9wU68TS1i8fiX8aQ9Hyl6KNea6s8XVxClHU60zovnfDXTN8ii4g0+0/eLmL0MI7kSxK9kkBobVjOaJbDUNNtWepFuIvBiyDC1DgDtKvYkugMUWCJbvYC5AfvnEulqV9hyxvwO0SyF1Kv706hWm0Ko1Savndu5Am5PI=,iv:B+46MDtq3ctiOsUDm2Mgil/ys3huwI14u8hrQJ0F4Z8=,tag:viYnazIuVMOM0KAwZega8g==,type:str]
sops:
    age:
        - recipient: age1svstfr65yepsdhxu3kxdy6t02gf6l779qxsqvd0dv2r0aqgzcpyqkwvl0c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMOExBcmNmaGZZOUZIa2NE
            TmtCQ1BYdUtHZDA3RmNtYXZ0WGc0SGQ4UldBCm9YczVkamZ3OUJxdE1nZHI1MkVF
            Wmk0b3p0N1N2MXUzVGtzOTErUHRLZ2MKLS0tIDM5RXJ0QjVrWmM1bU9KQkxpcVNu
            VTYzSS80Q3FOQmtSaDBaWG95Y2dTa1EK1V7isZ3XQDscXgdwojK9KVKSkTcVBfQU
            TYXORs2LsMMQT/J6IJzdj2qBU99XcGYRHwUAZVghmDvyna04k7M2Ng==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-31T12:27:39Z"
    mac: ENC[AES256_GCM,data:Hkhw6g209AsNjZB5h2DtzTlCWYTNGUzKNFj03Djw0FmaRLUhgoBeS9gBgrl87IESDe/3GT9Z1pn0xIP0UgoFTsvEFSSerPd0WuOdJAkHKAISQS3/w9dglb1NPlfoQf0JB0OoCX6ZiR8dEUl6OPl4sELZ+JzH5RSuIo6agTUjHE8=,iv:ib0TvjVQO+1uN60gejn1+IkO7i+cQuO/n2rLNlFVWCo=,tag:ZKufUulX3DFnSFP9XZCWyQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
