apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: forgejo
  namespace: forge
spec:
  valuesFrom:
    - kind: Secret
      name: forgejo-database-rw-secret
      valuesKey: host
      targetPath: gitea.config.database.HOST
    - kind: Secret
      name: forgejo-database-rw-secret
      valuesKey: database
      targetPath: gitea.config.database.NAME
    - kind: Secret
      name: forgejo-database-rw-secret
      valuesKey: username
      targetPath: gitea.config.database.USER
    - kind: Secret
      name: forgejo-database-rw-secret
      valuesKey: password
      targetPath: gitea.config.database.PASSWD
    - kind: Secret
      name: forgejo-database-rw-secret
      valuesKey: port
      targetPath: gitea.config.database.PORT
    - kind: Secret
      name: forgejo-admin-user-secret
      valuesKey: username
      targetPath: gitea.admin.username
    - kind: Secret
      name: forgejo-admin-user-secret
      valuesKey: password
      targetPath: gitea.admin.password
    - kind: Secret
      name: forgejo-admin-user-secret
      valuesKey: email
      targetPath: gitea.admin.email

  values:
    image:
      tag: 14.0.3-rootless
      digest: sha256:3bde16a366e57f37c09599b77ceb83ed05b1934f8224072f8140bc66cf243608
      rootless: true

    persistence:
      enabled: true
      create: false
      claimName: forgejo-data-pvc

    gitea:
      config:
        server:
          ROOT_URL: https://forge.superkooka.com/
          DOMAIN: forge.superkooka.com
          SSH_DOMAIN: forge.superkooka.com
          LFS_START_SERVER: true
        repository:
          ROOT: /data/git/repositories
          DEFAULT_PRIVATE: true
          DISABLE_STARS: true
        repository.signing:
          SIGNING_KEY: 0423CBB528FD933CA9209313A2E4E72A8571B586
          SIGNING_NAME: Forgejo Instance
          SIGNING_EMAIL: pgp.forgejo@superkooka.com
          INITIAL_COMMIT: pubkey, twofa
          CRUD_ACTIONS: pubkey, twofa
          MERGES: pubkey, twofa
        lfs:
          PATH: /data/git/lfs
        signing:
          enabled: true
          existingSecret: forgejo-gpg-key
