apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/media
  - jellyfin/volumes.yaml
  - seafile/volumes.yaml
  - seafile/mariadb-secret.yaml
  - seafile/admin-secret.yaml
  - seafile/ingress.yaml
  - discord-quote-bot/volume.yaml
  - discord-quote-bot/ingress.yaml
  - discord-quote-bot/secret.yaml
patches:
  - path: jellyfin/helm-release-patch.yaml
    target:
      kind: HelmRelease
      name: jellyfin-helm-release
  - path: seafile/deployment-patch.yaml
    target:
      kind: Deployment
      name: seafile
  - path: discord-quote-bot/deployment-patch.yaml
    target:
      kind: Deployment
      name: discord-quote-bot
