apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: grafana-helm-repository
  namespace: flux-system
spec:
  interval: 1h
  # https://github.com/grafana-community/helm-charts/pkgs/container/helm-charts%2Fgrafana
  url: oci://ghcr.io/grafana-community/helm-charts/grafana
  ref:
    tag: 13.2.5
    digest: sha256:0fcb82fdbf9409a24fb0f9b4c20875a2d0fa668d4f3ad71f1717845ba9bb99ca
  # https://github.com/fluxcd/source-controller/issues/1932
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
