apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - jetstack.yaml
  - bitnami.yaml
  - grafana.yaml
  - gitea.yaml
  - jellyfin.yaml
  - nvidia.yaml
  - longhorn.yaml
  - nfs.yaml
  - rustfs.yaml
  - github.superkooka.yaml
