name: Renovate

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"

jobs:
  renovate:
    runs-on: docker

    steps:
      - name: Run Renovate
        uses: docker://renovate/renovate:44.14.3-full@sha256:4fbdce22a4776f284b00919645599331588f9e4c88a1f80c09d333b09911a0e8
        env:
          RENOVATE_PLATFORM: gitea
          RENOVATE_ENDPOINT: https://forge.superkooka.com/api/v1
          RENOVATE_TOKEN: ${{ secrets.RENOVATE }}
          RENOVATE_REPOSITORIES: ${{ forgejo.repository }}
          GITHUB_COM_TOKEN: ${{ secrets.RENOVATE_GITHUB_COM_TOKEN }}

          # Should be a read only token
          RENOVATE_HOST_RULES: |
            [
              {
                "matchHost": "forge.superkooka.com",
                "hostType": "docker",
                "username": "${{ forgejo.actor }}",
                "password": "${{ secrets.WRITE_PACKAGE }}"
              }
            ]
