apiVersion: ENC[AES256_GCM,data:L8M=,iv:NBSSggcx1bK1XzYC4LQIe2k8pbx8xVDTIiEHdaoCSNs=,tag:QoU/bLDuWHOl0JpIxMCBSw==,type:str]
kind: ENC[AES256_GCM,data:5iO73bg3,iv:usaR8jUkbvCPsUa2Dl93xWn/fvnJVB+NoKykDMd/UAg=,tag:NeexyiQeKUGIvB8clSJRrg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:5lZA6/nDBKeSp0RRuPYkFdo=,iv:1+bzTURjqmoI4+sac9lsopW/yRCwvOI6ttas6xjul+A=,tag:aw94WQTCdvABZzOiLNlYPQ==,type:str]
    namespace: ENC[AES256_GCM,data:b0eOZscn1rM=,iv:idGpCI0HKPa5lSp5zcc4Z1HAzF4MMpXxYK3YuFXjH5w=,tag:hDHaU9T4CfrPM8uKFrnCUA==,type:str]
type: ENC[AES256_GCM,data:kahpIYVs,iv:GCl2aAFxHQ1K2ORrUgRQnN2rsgI0bvrppPX7kvi3ICI=,tag:jnVnjv4OV5FWDFVWWlU0+w==,type:str]
data:
    users: ENC[AES256_GCM,data:pz6JSU4kmkAm1JKUbGp1s3oqKqcdDowLXhPxVumWbrVTIn81c/czFhBD65WZSDeWH5pbe54zcDBwXpwq,iv:r8DFAj4NzD3BQmRklLWbPv5t7v+Upd1s0QESG3exJTQ=,tag:K2/eDb0iIsUiyrkuhK5jWw==,type:str]
sops:
    age:
        - recipient: age1svstfr65yepsdhxu3kxdy6t02gf6l779qxsqvd0dv2r0aqgzcpyqkwvl0c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUcjdacUlOanVpTXBRWVdG
            dVpwRm0yTHdUdElMYTQ2QmFyemRWd1RMRVRZCjFHVXR3QUtmYkY2K0xLN2MzY2tq
            ajAxNGZBYnhGZnpkeWJFdktMY0ppREEKLS0tIEdMNCtqcnZ5NW1KZEcxS1lRdWxr
            a1NPZW1VSnRCTzZDVG1UY05sK3g2cW8K+IBabnaIzY+Cv5LOlMzBbCQaG6jTSAtf
            SbKUVfgY5/5URmwVI8MVSjXSzQ51gVG9zoxzZlzmqW/XUH2jQBGkHg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-10T01:23:41Z"
    mac: ENC[AES256_GCM,data:OiqSVAUZigvNXH6GBYVWMJ6GBHM/sfUUPosyGpfigcyU+krzrz/lXvjrWXCHcWHBx0YDy3Nir3u6409ugQ4hkGPD2Rs1KTQOMF/v+s/v+oumyaOVbD3A3kjKqviPwRN44mGk5Id8mJc1KQBJWDr3GVNV6M0FvvUI9wXbRKY72Ak=,iv:fgmn8XYdj9D+vwh4nX/igLOBsGbKVqpLcQl8+Cl//aw=,tag:U07oPUFLIFxdhg5fRn9ZlA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
