apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn-helm-release
  namespace: longhorn
spec:
  interval: 5m0s
  chart:
    spec:
      chart: longhorn
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: longhorn-helm-repository
        namespace: flux-system
      version: v1.11.0
  values:
    defaultSettings:
      backupTarget: "nfs://192.168.0.11:/mnt/md0/longhorn-backups" # should be on cluster/home, global ConfigMap?
      defaultReplicaCount: 1 # single node
      storageMinimalAvailablePercentage: 0
      defaultDataLocality: strict-local # create pv on same node as pod only
    persistence:
      defaultClass: true
      defaultClassReplicaCount: 1