apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn-helm-release
  namespace: longhorn
spec:
  interval: 5m0s
  chart:
    spec:
      chart: longhorn
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: longhorn-helm-repository
        namespace: flux-system
      version: v1.11.0
  values:
    defaultSettings:
      backupTarget: "nfs://192.168.0.11:/mnt/md0/longhorn-backups" # should be on cluster/home, global ConfigMap?
      defaultReplicaCount: 1 # single node
      storageMinimalAvailablePercentage: 0
      defaultDataLocality: strict-local # create pv on same node as pod only
    persistence:
      defaultClass: true
      defaultClassReplicaCount: 1
    ingress:
      enabled: true
      ingressClassName: traefik
      host: dashboard.private.superkooka.com
      path: /longhorn
      pathType: Prefix
      tls: true
      tlsSecret: longhorn-tls
      secureBackends: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: "true"
        traefik.ingress.kubernetes.io/router.middlewares: longhorn-basic-auth@kubernetescrd,longhorn-redirect-noslash@kubernetescrd,longhorn-replacepath-longhorn-ui@kubernetescrd
    networkPolicies:
      enabled: true
      type: k3s