apiVersion: batch/v1
kind: CronJob
metadata:
  name: leaderboard-cronjob
  namespace: game
spec:
  schedule: "0 18 * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 3

  jobTemplate:
    spec:
      backoffLimit: 1

      template:
        spec:
          restartPolicy: Never

          containers:
            - name: generate-leaderboard
              image: forge.superkooka.com/superkooka/lol-leaderboard:1.0.0-alpha3@sha256:02d2c9791b39ec580453c85b6c762003c758c9fc2a3d35d7f4f55438e2d75dc3
              imagePullPolicy: IfNotPresent

              command:
                - php
                - application.php
                - app:generate-leaderboard

              args:
                - "-n"
