apiVersion: batch/v1
kind: CronJob
metadata:
  name: leaderboard-cronjob
  namespace: game
spec:
  schedule: "0 18 * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 3

  jobTemplate:
    spec:
      backoffLimit: 1

      template:
        spec:
          restartPolicy: Never

          containers:
            - name: generate-leaderboard
              image: forge.superkooka.com/superkooka/lol-leaderboard:1.0.0-alpha2@sha256:725d8f287d1881be09977a38bf68c45768cc431b2c35982f0caaee40022210d2
              imagePullPolicy: IfNotPresent

              command:
                - php
                - application.php
                - app:generate-leaderboard

              args:
                - "-n"
