apiVersion: batch/v1
kind: CronJob
metadata:
  name: match-cronjob
  namespace: game
spec:
  schedule: "*/3 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 3

  jobTemplate:
    spec:
      backoffLimit: 1

      template:
        spec:
          restartPolicy: Never

          containers:
            - name: track-matches
              image: forge.superkooka.com/superkooka/lol-leaderboard:1.0.0-alpha4@sha256:e4a14d746fe8f5dd96693691cb98dcac2512cf7e9c870cca6b97a03cf0b8ad87
              imagePullPolicy: IfNotPresent

              command:
                - php
                - application.php
                - app:track-matches

              args:
                - "-n"
