apiVersion: batch/v1
kind: CronJob
metadata:
  name: match-crontab
  namespace: game
spec:
  schedule: "*/3 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 3

  jobTemplate:
    spec:
      backoffLimit: 1

      template:
        spec:
          restartPolicy: Never

          containers:
            - name: track-matches
              image: forge.superkooka.com/superkooka/lol-leaderboard:1.0.0-alpha1@sha256:e2df99be622f335e2a2140e8462f99446d1c61bee747374d61ad02ea74d97137
              imagePullPolicy: IfNotPresent

              command:
                - php
                - application.php
                - app:track-matches

              args:
                - "-n"
