apiVersion: batch/v1
kind: CronJob
metadata:
  name: match-cronjob
  namespace: game
spec:
  schedule: "*/3 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 3

  jobTemplate:
    spec:
      backoffLimit: 1

      template:
        spec:
          restartPolicy: Never

          containers:
            - name: track-matches
              image: forge.superkooka.com/superkooka/lol-leaderboard:1.0.0-alpha5@sha256:0a3b121f540b5f7cb82faf692e25ceab269a08f281cee2d1d2919a3c9aea42c6
              imagePullPolicy: IfNotPresent

              command:
                - php
                - application.php
                - app:track-matches

              args:
                - "-n"
