apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/social/
  - baikal/databaseclaim.yaml
  - baikal/volumes.yaml
  - baikal/ingress.yaml
patches:
  - path: baikal/deployment-patch.yaml
    target:
      kind: Deployment
      name: baikal
