# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.34.5-standalone-strict/configmap-v1.json
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-config
  namespace: database
data:
  values.yaml: |
    auth:
      existingSecret: postgresql-secret
