apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana-helm-release
  namespace: monitoring
spec:
  values:
    admin:
      existingSecret: grafana-admin-secret
      userKey: admin-user
      passwordKey: admin-password

    persistence:
      existingClaim: grafana-data-pvc

    grafana.ini:
      server:
        domain: grafana.superkooka.com
        root_url: https://grafana.superkooka.com
