apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gitea
  namespace: gitea
spec:
  values:
    gitea:
      admin:
        existingSecret: gitea-admin-secret
      config:
        server:
          DOMAIN: gitea.superkooka.com
          ROOT_URL: https://gitea.superkooka.com
