apiVersion: ENC[AES256_GCM,data:roI=,iv:zmuwOuWxGkRULLi7Uqj114HCto6G+wht6+wUAJF8eCo=,tag:lYdHvzKo+EQxG+fmh001HA==,type:str]
kind: ENC[AES256_GCM,data:sc09Y+/o,iv:uzrRcPyuT+dsmgUR6onWSYetE7imTDrB5oR5ap1S8VA=,tag:aWBfvZSEfuIg+X1w/1ACkw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:qRmUJDiGGF43hGNy1xVcBbIS,iv:1FGPRhaVD/Xb2t56nZrHs7XfS9/qiudrUpCTipEEb4Y=,tag:KV5sGmGC32s43kOOVRkBgQ==,type:str]
    namespace: ENC[AES256_GCM,data:QojtRxo=,iv:zRBXGLgdzmnocbwU8wfIWfUxXY7J8Zt6mdVHxPavEsk=,tag:/warGe5LSBtWODnCSE7+kw==,type:str]
type: ENC[AES256_GCM,data:61CYBbUO,iv:FXz3ah+Tjx2e+6pX1H+jM3UdtaXSH60c5XNFhTJaMxU=,tag:hwcFVGHNuYAmGRvLkSoG9g==,type:str]
stringData:
    username: ENC[AES256_GCM,data:6To+vSc=,iv:qTarfoArvJ9f9Eskzwh5MpNLo0cbHoJ27KHNTmJcv8M=,tag:rAnUySTAjluHlokOp4OoRg==,type:str]
    password: ENC[AES256_GCM,data:zXP0UQNyhpEuDkMyl7lhkpjJOolSOg+cXnDjXoM=,iv:+zRhko7PaVS3PSyXvdOJ+92tdr9wKWPgh9BqfHCO8ts=,tag:VhJxlts7dC9LT6jKaAvZ2w==,type:str]
    email: ENC[AES256_GCM,data:/dL3Xo/r2CR1y61LW85260ZgqYM=,iv:6C8uRrhdNqTsupj7FJEdq7SajbclgvLPo0VupV7n6WI=,tag:MirkwPrvqQgq21+lTlY+9A==,type:str]
sops:
    age:
        - recipient: age1svstfr65yepsdhxu3kxdy6t02gf6l779qxsqvd0dv2r0aqgzcpyqkwvl0c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKaFVYWmMwYkdiemR2RmZQ
            MytYK1hHNXlkUm1xQUZ2WlBXR09QQkpTUnljCmNqQmp0ZjRRV1BxMWhMVnJOUVNN
            cFBKenp0U09HbW5CSjk2cDNtWlh6UEEKLS0tIGtGODdnNnVodEpocmdEWVlnNlJM
            NXFVdXR5eTlHb2xCWFNISWdJYk5laDAKEQ3wc0z11rf5QM5koCmCVRNvBAxx5tuw
            HHESokxom/VByHPL53HgGSoZ8+woLoEsZMSfBkq8J8A06LVHla/P2Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-04T18:43:52Z"
    mac: ENC[AES256_GCM,data:TOvo4K96qtOYHXDeUYGm+NKcX4yUQO7EyyUFqvXvlN97NQc/R1+CkJu5hA6A/T/HoNJkV3XMF08HYnTdud28gB4aX21nZZjSYoGmOnDZegnAl3bPOJ4cP1BxqD9a/s/q3p8553IXf75hVFfOoWHsoGFld2Wxmo03yELayjVDFZ8=,iv:niH4pSlmJ+/GNzn6ObwP2f5xBD+xp2GeczTVlObgBqg=,tag:LkN3bb4PE+9YczI6jD4QKg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
