apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/forge
  - forgejo/admin-user-secret.yaml
  - forgejo/gpg-key-secret.yaml
  - forgejo/internal-ssh-key-secret.yaml
  - forgejo/databaseclaim.yaml
  - forgejo/volumes.yaml
  - forgejo/ingress.yaml
  - forgejo-runner/runner-secret.yaml
  - forgejo-runner/docker-registry-secret.yaml
  - forgejo-runner/volumes.yaml
  - git-pages/ingress.yaml
  - git-pages/configmap.yaml
  - git-pages/volumes.yaml
  - perforce/volume.yaml
  - perforce/ingress.yaml
patches:
  - path: forgejo/patch-values.yaml
    target:
      kind: HelmRelease
      name: forgejo
  - path: forgejo-runner/patch-values.yaml
    target:
      kind: Deployment
      name: forgejo-runner
  - path: forgejo-runner/configmap.yaml
    target:
      kind: ConfigMap
      name: runner-configmap
  - path: git-pages/deployment.yaml
    target:
      kind: Deployment
      name: git-pages
  - path: perforce/deployment-patch.yaml
    target:
      kind: Deployment
      name: perforce-server
