apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/forge
  - forgejo/admin-user-secret.yaml
  - forgejo/gpg-key-secret.yaml
  - forgejo/internal-ssh-key-secret.yaml
  - forgejo/databaseclaim.yaml
  - forgejo/volumes.yaml
  - forgejo/ingress.yaml
  # - ./gitea_admin_secret.yaml
patches:
  - path: forgejo/patch-values.yaml
    target:
      kind: HelmRelease
      name: forgejo
#   - path: gitea_values_patch.yaml
#     target:
#       kind: HelmRelease
#       name: gitea
