apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: perforce-data-pvc
  namespace: forge
  annotations:
    recurring-job-group.longhorn.io/default: enabled
spec:
  persistentVolumeReclaimPolicy: Retain
  accessModes: ["ReadWriteOnce"]
  storageClassName: longhorn
  resources:
    requests:
      storage: 25Gi
