apiVersion: batch/v1
kind: Job
metadata:
  name: move-config-to-longhorn-volume
  namespace: media
spec:
  backoffLimit: 0
  template:
    spec:
      nodeName: og-server
      restartPolicy: Never
      initContainers:
        - name: wipe
          image: busybox
          command: ["sh", "-c", "rm -rf /dst/* /dst/.[!.]*"]
          volumeMounts:
            - name: dst
              mountPath: /dst

      containers:
        - name: migrator
          image: busybox
          command: ["sh", "-c", "cp -av /src/. /dst/ && echo DONE && ls -la /dst/"]
          volumeMounts:
            - name: src
              mountPath: /src
            - name: dst
              mountPath: /dst
      volumes:
        - name: src
          hostPath: 
            path: "/mnt/md0/backups/jellyfin.20250817160951_10.10.7/config"
            type: Directory
        - name: dst
          persistentVolumeClaim:
            claimName: jellyfin-config-pvc

---

apiVersion: batch/v1
kind: Job
metadata:
  name: move-data-to-longhorn-volume
  namespace: media
spec:
  backoffLimit: 0
  template:
    spec:
      nodeName: og-server
      restartPolicy: Never
      initContainers:
        - name: wipe
          image: busybox
          command: ["sh", "-c", "rm -rf /dst/* /dst/.[!.]*"]
          volumeMounts:
            - name: dst
              mountPath: /dst
      containers:
        - name: migrator
          image: busybox
          command: ["sh", "-c", "cp -av /src/. /dst/ && echo DONE && ls -la /dst/"]
          volumeMounts:
            - name: src
              mountPath: /src
            - name: dst
              mountPath: /dst
      volumes:
        - name: src
          hostPath: 
            path: "/mnt/md0/backups/jellyfin.20250817160951_10.10.7/data/"
            type: Directory
        - name: dst
          persistentVolumeClaim:
            claimName: jellyfin-data-pvc
