# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - pelican-panel/caddyfile.yaml
  - pelican-panel/deployment.yaml
  - pelican-panel/service.yaml
  - pelican-panel/cronjob.yaml

  - pelican-wings/deployment.yaml
  - pelican-wings/service.yaml
