# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/game

  - fivem-prod/config.yaml
  - fivem-prod/secret.yaml
  - fivem-prod/volume.yaml
  - fivem-prod/ingress.yaml

  - lol-leaderboard/secret.yaml
  - lol-leaderboard/volume.yaml

  - pelican-panel/secret.yaml
  - pelican-panel/volume.yaml
  - pelican-panel/middleware.yaml
  - pelican-panel/ingress.yaml

  - pelican-wings/volume.yaml
  - pelican-wings/ingress.yaml

patches:
  - path: lol-leaderboard/leaderboard-cronjob-patch.yaml
    target:
      kind: CronJob
      name: leaderboard-cronjob

  - path: lol-leaderboard/match-cronjob-patch.yaml
    target:
      kind: CronJob
      name: match-cronjob

  - path: pelican-panel/values-patch.yaml
    target:
      kind: Deployment
      name: pelican-panel

  - path: pelican-panel/cronjob-patch.yaml
    target:
      kind: Cronjob
      name: pelican-scheduler

  - path: pelican-wings/deployment-patch.yaml
    target:
      kind: Deployment
      name: pelican-wings

  - path: fivem-prod/deployment-patch.yaml
    target:
      kind: Deployment
      name: fivem-prod
