# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/game

  - pelican-panel/secret.yaml
  - pelican-panel/volume.yaml
  - pelican-panel/middleware.yaml
  - pelican-panel/ingress.yaml

  - pelican-wings/volume.yaml
  - pelican-wings/ingress.yaml

  - ts3server/secret.yaml
  - ts3server/volume.yaml
  - ts3server/ingress.yaml

patches:
  - path: pelican-panel/values-patch.yaml
    target:
      kind: Deployment
      name: pelican-panel

  - path: pelican-panel/cronjob-patch.yaml
    target:
      kind: Cronjob
      name: pelican-scheduler

  - path: pelican-wings/deployment-patch.yaml
    target:
      kind: Deployment
      name: pelican-wings

  - path: ts3server/deployment-patch.yaml
    target:
      kind: Deployment
      name: ts3server
