apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: baikal-config-pvc
  namespace: social
  annotations:
    recurring-job-group.longhorn.io/default: enabled
spec:
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Mi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: baikal-data-pvc
  namespace: social
  annotations:
    recurring-job-group.longhorn.io/default: enabled
spec:
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
