apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/network/
  - blocky/config.yaml
patches:
  - path: blocky/deployment-patch.yaml
    target:
      kind: Deployment
      name: blocky
