apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana-helm-release
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: grafana
      sourceRef:
        kind: HelmRepository
        name: grafana-helm-repository
        namespace: flux-system
      interval: 1m
  values:
    image:
      tag: 12.3.3
    deploymentStrategy:
      type: Recreate
    persistence:
      type: pvc
      enabled: true
    rbac:
      pspEnabled: false
    grafana.ini:
      plugins:
          enabled: false
      server:
        domain: grafana.superkooka.com
        root_url: "%(protocol)s://%(domain)s"
