apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - kube-prometheus-stack-helm-release.yaml
configMapGenerator:
  - name: flux-kube-state-metrics-config
    namespace: monitoring
    files:
      - kube-state-metrics-config.yaml=flux-kube-state-metrics-config.yaml
configurations:
  - kustomizeconfig.yaml
