# let kustomize rewrite the (hashed) generated ConfigMap name in the HelmRelease
nameReference:
  - kind: ConfigMap
    version: v1
    fieldSpecs:
      - path: spec/valuesFrom/name
        kind: HelmRelease
