apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyfin-helm-release
  namespace: media
spec:
  values:
    image:
      tag: 10.11.6

    jellyfin:
      env:
      - name: JELLYFIN_CONFIG_DIR
        value: "/config"
      - name: JELLYFIN_DATA_DIR
        value: "/var/lib/jellyfin"
      - name: JELLYFIN_LOG_DIR
        value: "/var/log/jellyfin"

    podSecurityContext:
      runAsUser: 103
      runAsGroup: 110
      fsGroup: 110
      supplementalGroups:
        - 1001

    persistence:
      config:
        enabled: true
        existingClaim: jellyfin-config-pvc
      media:
        enabled: false

    volumes:
      - name: cache
        medium: Memory
      - name: data
        persistentVolumeClaim:
          claimName: jellyfin-data-pvc
      - name: logs
        persistentVolumeClaim:
          claimName: jellyfin-logs-pvc
      - name: media-raid
        hostPath:
          path: /mnt/md0
      - name: media-hdd
        hostPath:
          path: /media/temp

    volumeMounts:
      - name: cache
        mountPath: /var/cache/jellyfin
      - name: data
        mountPath: /var/lib/jellyfin
      - name: logs
        mountPath: /var/log/jellyfin
      - name: media-raid
        mountPath: /mnt/md0
      - name: media-hdd
        mountPath: /media/temp
