apiVersion: ENC[AES256_GCM,data:9vM=,iv:ZGE+l55qlLQuzzHJ7dwLCUNeDzIoOopMsji9JEfhQtg=,tag:QMex0eBKHsMoOzHKXG1jGg==,type:str]
kind: ENC[AES256_GCM,data:nA98LGdr,iv:+dgy7l8VfMli1Xo30GWFkNUmERuias4ORwpEFOdg5ZE=,tag:KqFj/iZxHeWJMW3nXuIHoQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:1LjL2MFAJaHINK9NCLGb67VTikWUFg==,iv:zP2CMYyjslly3jBL1PmdCGElJakHkWzzSAHFSXT1mp4=,tag:WAcP2pthPDoGCMQRN/oS0Q==,type:str]
    namespace: ENC[AES256_GCM,data:Rxz85Q==,iv:R70+yEz/bsVH0r/fr2qW+59cK8LBH673NeD+rMX8rGk=,tag:kH/wI4pBgNfZBCH/S3r+9w==,type:str]
type: ENC[AES256_GCM,data:LxW/B7ea,iv:cgoSryfZpLSnjiU4vpHdq9Id5DDQXGtlLjiAEIm30QI=,tag:HnSKtA1U+6mbvok2FK/0zg==,type:str]
stringData:
    DISCORD_WEBHOOK: ENC[AES256_GCM,data:OZy8sfcRty0dJ4dw4bV1ENpR6Ry2YHE45u80xsBtl0/fzy0XH/+onvfONWA+OTxbhl+3hEgFN/MmeU5i2NVM0mkj8Euh8qjFnLo6rMWXDAIscdEGD/VrGptURpyHtnAD7cVtnQSySfLwEyGdlaCWYDgekWyvZk8/ew==,iv:E+UFQgvRzfNATz9fiOvLtHkr1cUvO03XdRvNM0iyPiI=,tag:XX24uBG5alpwXZgrS4pHqw==,type:str]
    RIOT_API_KEY: ENC[AES256_GCM,data:wsPwV4Rw9NjfzflkO47moDUjTVLbp7e50gq3jV8IKIFHDTwh9dL5E6PU,iv:m7ByYMfgk8YKC5guOZj4GjPgQD5okRyaVvyUbaKDQCk=,tag:Ij+rIwdoEF3EvLXQ8JrLIg==,type:str]
sops:
    age:
        - recipient: age1svstfr65yepsdhxu3kxdy6t02gf6l779qxsqvd0dv2r0aqgzcpyqkwvl0c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzM2FMWUdmd3NpQkMza3pp
            QnEvbkJLZjZjZVJvVFdCcVRRdG8wV3gyVkNJCmEvUS9tWkR4MERMZnQraTh6cHVK
            K1c4ZDFyc3RzdkRVMWI3VzhQRUxUL0UKLS0tICtvZkVFUG1yeVczbDhjUUgxMXh0
            S0daKzFJRXV6Q2RVdi9yTzVFUUNLVmsKHgoB3AYHpV/4McCbDTAQU4BaZgOT5ea+
            oWGGctQMSOouZWy+19rj3tVVWW/8B15gcZr/BIDAkcGpUOUhYk/LSA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-02T15:44:13Z"
    mac: ENC[AES256_GCM,data:Daa8IJ/R3hISeWpJho9Ly5V2ShAuPF2ysRP692T+Qf8m54rCAHBjaoXV06LmKUpXD1ybQhLUsI4sdccZ5U9zsQcUV8aMQQ0s14SGHEOBU9RWbfbNaQwq46eg3FiLNUHszSxr92gDFp6jn++++4m+dea2x0dJv/u24YXUSArqChE=,iv:kn0iepbIvL+Dd2N5vzTfRfk4wV9n4M19mIlRTycIMHo=,tag:uIRBPvx9TtVwK3W1aXE+JQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
