apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./postgresql-secret.yaml
  - ../../../infrastructure/database/postgresql/operator-helm-release.yaml
  - ./postgresql-instance.yaml
patches:
  - path: postgresql-operator-values-patch.yaml
    target:
      kind: HelmRelease
      name: light-k8s-postgres-operator
      namespace: database
