apiVersion: ENC[AES256_GCM,data:ePw=,iv:xw5XRXNwqBVa/YGZl4SffPysOBWarij1Y/lDPMr63uQ=,tag:OLsX8xaH3FoOf/F24yu3ww==,type:str]
kind: ENC[AES256_GCM,data:kAvoXbv3,iv:843fL0anZewQ7oQ0Fdh/BzikF8kWrW62j7BIQavDYnQ=,tag:CMGdgquY3F2f01ZW1ZHxSQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:OoQGKb1ixW8VqsxxrkmJim4=,iv:9oW8mf2pvk1nDkAEkkVwq2ac0IEddxvB5KZOfx9rT3Q=,tag:KXC5toXF2lVKkH6fKS8nRw==,type:str]
    namespace: ENC[AES256_GCM,data:MRcpdcxz6H0=,iv:WG4WJkuNHQVnryG3PocqozSDNOHQjhiKr4gb573vyEQ=,tag:35AKWK/wYkveChen6Tp5Kg==,type:str]
stringData:
    password: ENC[AES256_GCM,data:v87L00iGQT3VMyRMhrInjYZobXLH330R,iv:CalWR1WWX6TMiwbEo91DPMDW9Etrfft4wdZI+T44bp4=,tag:FLB78PS2zwFynp3EWTHjww==,type:str]
    postgres-password: ENC[AES256_GCM,data:4pUkJMlAGeJ73hr8PgUodD1EZ+AnInKj,iv:xT4ffuag2bAGToTkaU/B3lFe8qO8xKqvPvmUvsmE298=,tag:QMjuqKOz01iruPZN12e5KA==,type:str]
    replication-password: ENC[AES256_GCM,data:S/oiK2t6/WcIalY7HNKfYAE/Ow4xwgmc,iv:E0fI8UTtb07mnTfwGvheAZ6g9868so5k0HBRAtMBz6U=,tag:b0zOjyBk33p2AGRnLqc18Q==,type:str]
    postgresql-password: ENC[AES256_GCM,data:u5/T/WucB2NP8wyxXE1oeCWURZlGHt9Z,iv:+CQGKQDAWSc9d3JSAFueq+8PLedehYlMbG1ZCfkaK7M=,tag:VV6+ejHFHQTssFSx3PDa+Q==,type:str]
    postgresql-postgres-password: ENC[AES256_GCM,data:/sqEkqN5TwRhvsc8vAZ4qXv9Fcdp4Mcp,iv:dHZ3pIrz22uzm0zbPG3VxozsYDAWjKkibpjlDOpWCBI=,tag:bEoXzM8g36n7T+jFaTAdvw==,type:str]
    postgresql-replication-password: ENC[AES256_GCM,data:BstqiJ+XTlZrHVGh1zD5w952GKN34oE6,iv:yxbt6iXWiL4ztyaPB0+33ed4SgHE+lW76YkJvMkeE2k=,tag:5slvi7kXwobWeNQfSm5u9g==,type:str]
sops:
    age:
        - recipient: age1svstfr65yepsdhxu3kxdy6t02gf6l779qxsqvd0dv2r0aqgzcpyqkwvl0c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByTGdKMDZOUU1aa2tGWVYw
            RlkxMk8xU01KRUcvZG96RHZ1RlBjQUtuUjI4Ck9URWlwREQzS3ArM0loSksrVHg2
            K3VndmVGSEhLVDNqSGxReHRyK1RNZG8KLS0tIDFTMk5IOGFZa25UZnRrSTBIS0Yr
            M3hxQk45TVE2cHFLWXlwbDFBaElGM0UKe8WM+VtB0xpNOZXDvrQYQtmWmQc4PL9A
            xwxeQnXqW4Y6Zk0hrNXK8jmhPPYUYvEi3bqVWm4p+C4LTFqqBecGFg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-23T22:24:53Z"
    mac: ENC[AES256_GCM,data:IsuqijLoOC5LrwoThhJATI2umD7QzZoggHQm/97PzjD6cZ8AH62gJI5uMPlXwGIgiQWWDcTNgQFxToTLh8AefD5MCyCt49yk6T6znc7L+goQQgSpqmM5CFgH8Erwc3YPWqc70P9CC6OtwFGCR1b9Ea6+raGIRRrrTC7FDAfzN84=,iv:0ily5bjUn1qO522fqHkzpBQ5u8Vhl76pb+DzBz4JgXc=,tag:zjW2nSJpgGoDRUhrdqbqOg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
