apiVersion: ENC[AES256_GCM,data:tgg=,iv:HF+8s8GbVFZpTKd2TWdo2jhHDwucjAWT1ahDdb8epvU=,tag:c8Gu9XzVuEDPzTfcXq8/Lg==,type:str]
kind: ENC[AES256_GCM,data:NraVypPv,iv:CoG61jKx0g/3VJLSMaehGS1iIevRyNzR/Ep/6nYnEeg=,tag:Q+qrKcFrEi+KHQRpKaQHZQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:m1fN1wNvhaZQG4iLm8g7i6g=,iv:tmFYCOggCwLFFYI25QwTeURySdZf/zDb+uL1GDChL1M=,tag:50Po94LVyJp1RgCXPOUV1w==,type:str]
    namespace: ENC[AES256_GCM,data:sh60tV0qiGc=,iv:iAwvTU1FMra4lSlnnZ/zOnjKnXp+qA9CGDJ31qPiylA=,tag:f15x7LCwlQLOYKFOsdqgcQ==,type:str]
stringData:
    postgres-password: ENC[AES256_GCM,data:ctF8+MN5Ua22nxsPbHZBKLAx490Cb3uInM6bjryV3b5b2yPFiYuB8dMYTXI19Wn7iN2axBVYvjfiEjAIZBrSCajL9MbtCSIrmSdjgtEUdT/ruKTg8u//s7+fW6lLIXMc,iv:V12LNOZsrT8cwmoKn0nsrnh6qyg/iVWQsGgqojkqXJI=,tag:1hMPVYbR5V0Ym+bZVakkXQ==,type:str]
    postgresql-postgres-password: ENC[AES256_GCM,data:gxThNBjVXnSe8sjsu9E2l6gR8wMrAHnt2fAYR8KIs6AHK2jlX9bYg7vGmCdOj/G/YcRD7YfpaZzbqIPMiio4UMf6Gc6XhdkR7dzeJ5j2S1z1tB8MpgqPdiIpUbLAAqoM,iv:F9k+W9VFBr+syXz+MT5iT2xtknyniCWe4J1umefQfFk=,tag:DSz/6XZPQEnEdEF5fjusfQ==,type:str]
sops:
    age:
        - recipient: age1svstfr65yepsdhxu3kxdy6t02gf6l779qxsqvd0dv2r0aqgzcpyqkwvl0c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2clZFQXpqaFdVa2doZkw1
            MFQvSEI3WFFoWDlRaFhqSG1tcjhPQkZhRkRBCnNkeVZrTURmaWYwNVJXYzM4UG53
            UWJNWmpTbHM3TG9vQ0Z4WkhmMWtJUE0KLS0tIFZNeW45VC9obXZEZmltZWRwWkJy
            dXBGSFdRdno4VkVhcDZMcE1Ha1JsVkkKoFpNipUSiCsuHOfMymM1tYI82HiumpzG
            kRBklzs1eM4EOZQ2nxcYQu2Sm3RML2i73YLolpVC1A9fPSMagxJEmQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-23T23:45:47Z"
    mac: ENC[AES256_GCM,data:D8dSi+WVs5zAVbPFgeFUYCCPQ9YHJnUYFwMFkaNYxWN0B5djHm1jo7Sc4A8xViuTCLEQysHVJ2ytrZBUwaHlcmszT89DxMbUq4uWtjmGM9khWtJgTCapx4qt/D2q7MyH4rbUMDP3DzbcHpfyVOvzgiSf0gGvyVyW7qGpE/XDoEE=,iv:9rtUAMtR60hr95VNjecaw2GoqZeh0VYzmDuWzDuG8I8=,tag:F/dE26Iird3i7LtqGazwLQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
