apiVersion: ENC[AES256_GCM,data:wtw=,iv:5aR2PGPkOTx9Aw7mU5FxRgP8Zu9Kq8oXQ8/tWTwAR9o=,tag:KZ7/IvJbpSsh+PwxQKKL1g==,type:str]
kind: ENC[AES256_GCM,data:hiRYkocK,iv:VbBgLEFdQjojWHgLEjyyTYTat7PJMhULiSTJNXPIuMo=,tag:2ak7I23wUKOzwYmJf+Xx+Q==,type:str]
metadata:
    name: ENC[AES256_GCM,data:NrPmgPQYRzbg+iiv+/bZzZo=,iv:42gnPRBE+IAlm6IFF2thr9hCPEHvc8BLetOrrviUlU0=,tag:xa6dq21whk9SqHOLm3skKQ==,type:str]
    namespace: ENC[AES256_GCM,data:o9/JOwUQxKE=,iv:N+/CGv3+VQxNrCRL9fc7ideUrIw8Ua8+6iMYTk+EkQQ=,tag:9R3olQ1ET1rw+zqcisRM6w==,type:str]
stringData:
    password: ENC[AES256_GCM,data:tZ8nsCKIrcV+NKNuEO/RboGMaVu7szY1,iv:ntFA/IDijnLcCouVoGSPJex3s32iTz/KkrIfbJw+3+M=,tag:6HeXulnTqd3P6enJcT5ETw==,type:str]
    postgres-password: ENC[AES256_GCM,data:nGwHnkYsai8JgG6bySvEaDeIqzaJcZtz,iv:VzcZWSeFiBRsAauZu9zgxWQ66bnLChTMAedCgj29K/Y=,tag:6BaGievzvDF1K5VOj6Id2w==,type:str]
    postgresql-password: ENC[AES256_GCM,data:DKqAT3YQtlpBnOU3eWM6ST4UcVYzCXME,iv:KAbbt2NR78V2EUtVIlOMaHmV4Lead39Di/x/1vyt+nQ=,tag:eaislEBBz8KG72H/D1JQIQ==,type:str]
    postgresql-postgres-password: ENC[AES256_GCM,data:j50If72GHJRNAHRq5sowUMxcUQ820LKq,iv:5Uk042FB+j6B1PaE+8eFA6uxq4Dbg+J6keOAutSxBEY=,tag:5K6VCp+UDQQwz8flj23z0A==,type:str]
sops:
    age:
        - recipient: age1svstfr65yepsdhxu3kxdy6t02gf6l779qxsqvd0dv2r0aqgzcpyqkwvl0c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5VDZXYnMrczZHWDY4em1m
            cEw3T2FvMUNxZ2ZScmx4a2pCV1lmNzdUOURZCkhMNGgyOXArM1pZN2c4VjlnYitR
            UDZyUTBUOUgvTlhpbHV3RExuTEhrNW8KLS0tIEtoVmd2L2hPSDdvWVlPb1gvQ2dy
            ZmVWdjhab2JNY3NTQjlXMzBsUm04cGsKvTpyj9pMh5MOb8k/dunIHvzjBVN5zdAh
            5dV9DQzMnq3q+FmC3UNORKj8DtjRiV6XrxUx5CSQ1jCCObHuPrISQw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-23T21:57:31Z"
    mac: ENC[AES256_GCM,data:9m2yDgAvHOZEhoLIoCPm78o7utqTBUJQgzrfqYzzfiu7pu/pMI/lwEvwMFf7/gTusewjWTVq/ldtIGI+xxqCHhJVOIp9indo+I7AaHeNsey51LYLHCJ2WMhjw8bgWokxPu1LOtNNblpVUKqts18SPFtVyDHmGvFpJEy3AFjgWQk=,iv:U0p29/OEpDH7U+TPALoo2cnnto9D4ppUnqeMvWWYOkQ=,tag:M7rAZSN0yRZEkN1X4beQ3w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
