apiVersion: ENC[AES256_GCM,data:u0E=,iv:EEDV0QNzNO8pN7HCcE8iIFVmbOhbSW9HAEWl1QSDSZQ=,tag:9H8ql39XpyosYJC9kKGOUA==,type:str]
kind: ENC[AES256_GCM,data:uXzMWQW4,iv:CxS0p+xUIJiQsCcr5aSEP19ys3eKp0YjP8ygFPYvdHY=,tag:gSISO4IQS33hnnse++zpKQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:MOKdi7A3Wk3Ts0FaRh9pKoQ0WNg=,iv:0wGyLp4vOMc+xGam3bQmfYRFvhrxrd2cg02I8Slk3fQ=,tag:J/cMPUR7neRny9eSqzdlKQ==,type:str]
    namespace: ENC[AES256_GCM,data:q/bs5o4=,iv:OV3cp9C+cjH381bS1Vhx5PQo515oCKgEoNz/wMfKYdI=,tag:1A0F0vTkifYW4f/pJBQrAw==,type:str]
type: ENC[AES256_GCM,data:sXkwfP3T,iv:8zira415lp60zhDiYHCG5yBB28zenoXH2JRGcNHbRMU=,tag:Dm54TVnZpXU9F9wsTp4WbA==,type:str]
stringData:
    email: ENC[AES256_GCM,data:XB4e5o0Fi+YJiKn9QMSqsf6ATko=,iv:khMgj9RxDGVS6MNGp8F/KBMuPNw3zjBpTO6fOHV5Esc=,tag:zB5Bj9kgvn0pMRralS5d8g==,type:str]
    password: ENC[AES256_GCM,data:ZVvKIiORKRMurRTekicqhb5NJH2W28a+,iv:X7HXxye3spbputCH83PskYoo3Z1QNSH4PoL0NlwW/wo=,tag:TPwS8IVcf10cJNp6lk7psA==,type:str]
    jwt: ENC[AES256_GCM,data:BN/JROeidjO3AVqUeWeBc34LsX6Tg1+zqtMYfWGmAA0vgm+IH0KgjQ==,iv:Cus+Zadt4gtPVzmWar5T23bwjEjprmFD7nPc6vqEqz4=,tag:Q4Ss6lFCGbUgFTqcprxq6w==,type:str]
sops:
    age:
        - recipient: age1svstfr65yepsdhxu3kxdy6t02gf6l779qxsqvd0dv2r0aqgzcpyqkwvl0c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVVDM5ejA2dS9PcVo2N0g5
            ZkFHdi9hbng0UTMyNUI2Nkc5bFFuR0g0cG5VClF3S0NleUVXdytuTHpTeWFXaENn
            ZjRWRUpNZnVzNFZmdVpubHV0MjhKTWcKLS0tIEZNbTBUbGEwU01Yam52WTRZMUR5
            UzN2bThhcTY5d25Qay9nQjZJZUpkTUkK41/+jDOdGgQKY9TMG1OiD+yoIZzsAKck
            wDL4plWumk9w7CnUeqEp9ZePt34VLs5j40cFMAreO5slrvs5uPweZQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-30T18:33:57Z"
    mac: ENC[AES256_GCM,data:uqd8dYc9SHoyWJ30Mr3MXkdTTUI3epe7sA8YqdA8hwMvZai0epxLuakY5AH6DqV/jyB+SGd89l/koJmx83uZxc2tF2YrTXeM2/VH78gmmvGlG1dxxzNl8+a24btElXmHso5eOLd04+SoH73T/EXhg8F17M+OQ5+WURreaYQY0k8=,iv:+qTfRcfZEKA//FpBb3q+t05sG73usodglyzFPb/IJBE=,tag:4XaYV0QOolEkU3FvSlmJoA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
