apiVersion: ENC[AES256_GCM,data:VWc=,iv:7uiPR6kvfQ7c/yj2iakOVXdspGQLa7bGNcxLI/sACsA=,tag:0rM2guY8C34/ypjf7NJ3nQ==,type:str]
kind: ENC[AES256_GCM,data:G7ZIfLfm,iv:NOih141hxJnPzwhJvOEsvk8bQ2A8gnhXhZwh1b2UcTo=,tag:6C3Jx5ZabZIqIEvC1S56cg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:SwaHN4CSmMpeClZ6QwQLKLyEOqASsQ==,iv:Lc/dz+P6JsqT5wIjRHYv9RMm9WhdKChy1ko04tq1wYg=,tag:NAEg0Mcte1hMWalk9J6t/w==,type:str]
    namespace: ENC[AES256_GCM,data:Q+r5i+Q=,iv:QLiS+wQxyGMgmbebTaCWUhQio9WyiWPrgZntDED1Ftw=,tag:rhNwctLi6rm6KByNGhX+rw==,type:str]
type: ENC[AES256_GCM,data:dzMNPVrN,iv:+xfMVXooIw3oUJcDG9D9gJpb9u23wCem/pOD1xUj9Ms=,tag:oNMwwPxK9udBbWY3xqllMw==,type:str]
stringData:
    root-password: ENC[AES256_GCM,data:1QkNrKMFI9DMuljZ4t6Mf4AxWGVhry71TmolQYt3BupELO4aQNBsdm7yUjUq/6gJziXXc1cLZ3QNC9HWQBOXKw==,iv:tFP/p/aE3a/9bBda+uDs6fQqc3ody7STY4H9S95BJhY=,tag:SfGXR9OrRBd8JePNoJ1cVg==,type:str]
    user: ENC[AES256_GCM,data:HzOlnck0rg==,iv:fEKJbW0SWZDknRJv/lH6pm91v3AO2Td6mPmVQ9avlqg=,tag:1CbsAxZsw+A2Td6Y+51IQg==,type:str]
    password: ENC[AES256_GCM,data:YL9a/1q9vSql9O4srtdIms9j5b8i5syPcnR3gcbphSiFdfBjyw2W9uIWzE0H1U1D8y/ahun9tO5mkjZzSffJww==,iv:nCjkikzLtdpKwYl3gnRIvcqqKIExSLd9kx+4l+n7h9M=,tag:o0EeomdeG2vhddBieS9nZQ==,type:str]
sops:
    age:
        - recipient: age1svstfr65yepsdhxu3kxdy6t02gf6l779qxsqvd0dv2r0aqgzcpyqkwvl0c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2SWx5QWR1M3hxd1V2Nm13
            UVVCZ2o0cWFjYXlzV2xHenBVMUs5dmlsbkNZCmV2TU5lYUdiZjVRK1Y0M2Z5VWRL
            SFZMZ2czejJ3K2NHNzBrbUFHVkh0aDQKLS0tIGVabExmYnlxczU5QXJnZWJoUGlV
            cEJJazVlb2FvNzZIRXpTU0NBdXJHY3cK4OMAfsRJ/panjdLQcsIGvidk1gl6z87W
            J6KsiZArsM4JI9KgSEagVyr+WbHnSgpmmTs41ny12TH5GtmI1MoyOw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-30T16:27:57Z"
    mac: ENC[AES256_GCM,data:RYcOSiV/luF9XCp1y0jkSPNXCs5Qxz6YrVZy7E8udyAu8vtMdT+o82cGDk23VodWhsax8R7CxFC8QFNJ16k7vPUabI2MhuePLB3gKrfm7RDTBb7eGBBqGVtCJiwWEb8BupcbqJMxPggsX5DCg3aVNykmktfoZ5j3eui3Unppp0U=,iv:hQ9FYHtp//JyLx+4byIWt9qNme1tN74VLw+QH0bb0Mc=,tag:qtPXjrYXREO+nVEtet7SRQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
