apiVersion: apps/v1
kind: Deployment
metadata:
  name: seafile
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: seafile
  template:
    metadata:
      labels:
        app: seafile
    spec:
      containers:
        - name: seafile
          image: seafileltd/seafile-mc:13.0.19@sha256:3483711551088e1e3423ec2ee933dccfdc779041b11191ea5a943e3225b15637
          ports:
            - containerPort: 80
          env:
            - name: WAIT_FOR_DB
              value: "true"

            - name: SEAFILE_MYSQL_DB_HOST
              value: "127.0.0.1"
            - name: SEAFILE_MYSQL_DB_CCNET_DB_NAME
              value: ccnet_db
            - name: SEAFILE_MYSQL_DB_SEAFILE_DB_NAME
              value: seafile_db
            - name: SEAFILE_MYSQL_DB_SEAHUB_DB_NAME
              value: seahub_db

            # Cache (Valkey)
            - name: REDIS_HOST
              value: "127.0.0.1"
            - name: REDIS_PORT
              value: "6379"

            # Memcached
            - name: MEMCACHED_HOST
              value: "127.0.0.1"

            # Fuse option (montage FS)
            - name: SEAFILE_USE_FUSE
              value: "false"

        - name: mariadb
          image: mariadb:12.2.2@sha256:6a4c4bbf0447c2247801309513fcc0dd17c3f35390368139ce419387fdd1144d
          ports:
            - containerPort: 3306

        - name: valkey
          image: valkey/valkey:9.0.3@sha256:3b55fbaa0cd93cf0d9d961f405e4dfcc70efe325e2d84da207a0a8e6d8fde4f9
          ports:
            - containerPort: 6379
          args:
            - "--save"
            - "60"
            - "1"

        - name: memcached
          image: memcached:1.6.45@sha256:eeb9eaa939ffaa2304899674c9e88a9247ec8e5e40e424a892df7b09914bd2ec
          ports:
            - containerPort: 11211
          args:
            - "-m"
            - "256" # MB
