apiVersion: ENC[AES256_GCM,data:uaE=,iv:5QxrfyKOJdjsgaH3qax2bjcxYsXyKPTB0Ck/hz5clTE=,tag:J1RzDa2rACL5TwIzEv9UTQ==,type:str]
kind: ENC[AES256_GCM,data:b2+Wo2XV,iv:h5SQ9HYcAR0Xdc2DYrgH5aZZcZC90dZOHBrLVZ2orsg=,tag:6R9VR8L/+YF4yJkO9tWQdw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:wd9tKq04IhuMrssfagQw7P4=,iv:B9j5zPLsmOiN9YVxP9ohj4JqcOOvJI0keiGPO3MMWK0=,tag:HS31x7MQKzG/OEtaJZY/Vw==,type:str]
    namespace: ENC[AES256_GCM,data:VJRDcHXovCw=,iv:jV9rOWnlhQO/YUqyu4pDZjTlnQRn5PQtEWISyM9Eb1s=,tag:I666hhoV8+XgTzYIJJDXvw==,type:str]
stringData:
    password: ENC[AES256_GCM,data:wr43QJBoSvkLNWO+ID+T6bfBicZoHjxg,iv:B8Xqco75y2/Q98WJ74IACAP04y4qcY/ov0vXU+BF8EQ=,tag:2+J+8KEn4qE9XYEaR+QVEA==,type:str]
    postgres-password: ENC[AES256_GCM,data:72gXCzU3084UAusH3j7NkA9qeiP/r1d2,iv:wxxRY9qYge8HqUfx7J6tKUNhYeXOlpMR3cBNcR2aX8E=,tag:CGXTJ4H8K+10Sj+m4Nhxuw==,type:str]
sops:
    age:
        - recipient: age1svstfr65yepsdhxu3kxdy6t02gf6l779qxsqvd0dv2r0aqgzcpyqkwvl0c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4REhKbGRRWFBELzRpb0JO
            c2tXNVlyTXRYZmQ4eTBVNzltQUxOSnZxMEZzCnFUNFNxMnozd2JydmFVOTF0RWJt
            QlRUNXRBcVptNEkwOTVxQnVoVm5kZWsKLS0tIHNaS3ZBNkppa252WXpVL3Y5bEN5
            WUlCUUJRZkoxV3RpdU1ESGh5TFAyem8KfCWdGuZA6EvrPwGmJkwFY+TN4TLCaE9P
            C6NaWKCp/t0ZaIKIkDADmXEAPlxYNnUR9YqJI6jL2GOw775jVUSm5Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-22T17:15:47Z"
    mac: ENC[AES256_GCM,data:yuaz40y26IUoWjL8fCAjuGD9M4+YSOzIHfJJvdJ8D/kuXZbe9p99rzDL7frx+5hEfT0SUusPzjX6FR64K3PCv1IzxRZ4pH88dsPfNivmYtM7V6N1t2s83RvS6nh2gjU6wakY1h5TTPKwXHzKBRxEb0QBIKuzXppPnQsBMv+kEYE=,iv:lAyQYEzzRyG+Bg/bIPnd7veKfKgVy/fF05ZMu0vGxgg=,tag:u7nVeu3pbzqgAdUSLW01ZA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
