apiVersion: ENC[AES256_GCM,data:xaI=,iv:BkUlBL/OvzSH0R2Giex5w9/nCXIrz5hoMSloHzBam4c=,tag:kuCVaDWK/HD7ECINNmHTZA==,type:str]
kind: ENC[AES256_GCM,data:HbvdEkF1,iv:6FqMsMgj5jHqY0SjbpyijF+6/sGCfN6y7ne8iALkwe4=,tag:is0W2B5KuqUTclmUic0Y9g==,type:str]
metadata:
    name: ENC[AES256_GCM,data:i8bTfDOr/BDo8xJRRpE=,iv:om7gjFfXlFiigaJoaCf4ufdcl9Ujkq2bptXhKXGOddI=,tag:pPuuIFTaogpE5wZMYlYKhw==,type:str]
    namespace: ENC[AES256_GCM,data:i35t1A==,iv:S/tsX4NkWuIdct2rdtsgCuf/NpDvrMsbQ0cDx7U6kjk=,tag:AXMICNP/CNMLF6pGpWqW5g==,type:str]
stringData:
    APP_KEY: ENC[AES256_GCM,data:9brpz01tHC4SYnGfT8tkBST//HidAEvAv9bVwylr5byVAIBsQqI3saOVOHXdPiv6Shan,iv:OwhTANsV8XFQch1f0GSIDpCxL0532CIwO1fWHg145Fo=,tag:eI8Map42MlSyt4ZI1Tov7w==,type:str]
sops:
    age:
        - recipient: age1svstfr65yepsdhxu3kxdy6t02gf6l779qxsqvd0dv2r0aqgzcpyqkwvl0c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRWWdtOXlkSHcwcWpNelNC
            R21ZZXBlQ2tIemdpMGtzZ2twRENKbmNXMlh3CnFPNS8wTElyMGJ5VFlkZytmWUh5
            T2hVOXRvVkdDUWNJdUZlM3dWR3ZNRzAKLS0tIFg5V2FjVVk3bS9TMU8za3NGNTgr
            clQ4RkdycEZXTENvemdJT0JwNjlMVDgKNVL39HzI6PUXOwO2Mvdd9hOIwndoR84Z
            5A1mKM/F4TNMA7gL14NJ+ttt5cbXBvBVXFLLf9klnnN/8GiQa2BLjQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-24T15:46:20Z"
    mac: ENC[AES256_GCM,data:2zM1V2NsdGHuWpyfxJQ2hRsLnmr7lGWmIEGferuNmdZke2cRgi+5hiVrt/DXWFXPQKaPLx3Ps6g6Fk7jRbH9VaN0hzNF4zDVRmeA7U5jzcvmnhJDrge8vxzwvFn8oiVDwELMBR89Nk44wlKZ0WndevovSxVSqvNHUdl1sOzxcnM=,iv:PLpRDwnfZguHxBfdXNRwtx1YF87hS1Uq/+LzO7ruC7I=,tag:I23dKZO9pE+ll0KUwXyHjA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
