apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pelican-logs-pvc
  namespace: game
  annotations:
    recurring-job-group.longhorn.io/default: enabled
spec:
  persistentVolumeReclaimPolicy: Retain
  accessModes: ["ReadWriteOnce"]
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pelican-data-pvc
  namespace: game
  annotations:
    recurring-job-group.longhorn.io/default: enabled
spec:
  persistentVolumeReclaimPolicy: Retain
  accessModes: ["ReadWriteOnce"]
  storageClassName: longhorn
  resources:
    requests:
      storage: 20Gi
