apiVersion: ENC[AES256_GCM,data:Z7I=,iv:PDDQOM3/ZKWNHbd/oU9ZZg0NYscQ9fZiS8ba5mS5MEQ=,tag:oT7qCbaQqPO5LaKgQOY/fg==,type:str]
kind: ENC[AES256_GCM,data:ZwAg+mbL,iv:IYQ6B6SdgplIGGRXqqxkGTAOCl0wgUuA4LsHJBJpFpo=,tag:GpR2IA8jsSMTzUDkP65bVA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:THEouKs5Rrfa4JUlA7tX,iv:cLzUDvU+Y1FSsXODXzJR2cN7htnPGSJr/pyGGh0Ih5s=,tag:EmYpRJjNWfjyxTTfqXKiUg==,type:str]
    namespace: ENC[AES256_GCM,data:W0nUPKpjCHc=,iv:Xv8EuLfmMGMcDwDj/iNovb0VIEvj+RoJMKTMb0cdwuA=,tag:UfyMyCCBo9b49MsqNQyfAQ==,type:str]
stringData:
    ADMIN_USERNAME: ENC[AES256_GCM,data:IYNndGA=,iv:QzCxB+WntyTFwk0YmGCtq6xXi4cHKTQyySo04SnMKfo=,tag:8Rl9sk/VsJiE2gqnzFIQuQ==,type:str]
    ADMIN_PASSWORD: ENC[AES256_GCM,data:epUY7nP9cascmlNmbr1dzm6b1Nwzsgxx,iv:ABxD98bWMJhZbp8XKJoMtyFrQ24OLKgxsmnxZ1FQsrY=,tag:VjMB0tPUBVDe8taZU/DOwQ==,type:str]
sops:
    age:
        - recipient: age1svstfr65yepsdhxu3kxdy6t02gf6l779qxsqvd0dv2r0aqgzcpyqkwvl0c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCRkdLQ3o2dTJrTGxrWmNp
            NVY3RW05b0g2anZ3eHhwMW01alBmTWw0U0dVCjQ0SmtpKzh0WE8ydWRLYSthbVRW
            ZDZ1Z3Y2bmd2WXhRZVhwSHhWL1JnRHcKLS0tIDBqOFdqbkJsVXJMbzZUMi9zNmt6
            UGozaGZxOE01WDlQSHYzYmNtMjBaa0EKcivK0NlO+dpoGCiL5sPre/tgCJd9Tjs5
            6sWAK19/Yi3JVBfYiLUT/xCQGArNDsHbKvhYkwzhWxbgJN7hOuhruQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-24T13:07:04Z"
    mac: ENC[AES256_GCM,data:JjbNoKCLWfGd+LZ5xtdasPK+Ds4bPnoSbviR20s1t6gsUi7Ki0qGxbULrFNYdvDr0V86IqFhXPwd4wVBgiSTtWx4l95CVo1l5oN0hICMPtU2EX932uFFPyCPFCUcrmGOm8ywyGW9xb3RSVdh/KBDJEuZpjHtnzoHuCNhQa/0QrU=,iv:/MN0KxL3ePsaXhZzdPENGWUeIPhr/X8OdLAqq5wN3a0=,tag:OaBo8Cq0pwuOc1Zgboi4ZA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
