apiVersion: ENC[AES256_GCM,data:E28=,iv:o2isKHGiUYIIB5U/kJDRdA+8Egu4FEGAPBqLbEcO+vI=,tag:+jiM+l9QvYbQ0sc1yf+Bjw==,type:str]
kind: ENC[AES256_GCM,data:Atui5O7/,iv:Unq9K0Ve5ukIgb7K/hr7GzlOdNblZUshvAMxF+bjq4Y=,tag:o/DpC5bLA2Khfa2Arw70UQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:gV9kxQ1C/h83ulkR,iv:gIQdf2Mc1p6Gv9rhvAUtgqt5opVMs16aWBoCZTKH9Ec=,tag:mh07otNQiYj+0ZA3rO+kZA==,type:str]
    namespace: ENC[AES256_GCM,data:B5wnbdw=,iv:aWPWLApGtqwaPPcBlExiErn3uKSoMKpFMFSl1au9RnY=,tag:gRIrFnjobmNN3DfyHfIBYQ==,type:str]
type: ENC[AES256_GCM,data:EjNRc6Dy,iv:wu2ZQN/vYEd6GRgDFQld2rUuxpCcks63Wlp+OAcmxdc=,tag:9lNcVcFUIXK/R6JyC2+dhg==,type:str]
stringData:
    username: ENC[AES256_GCM,data:/EoO7LPer3REvw==,iv:diSu8asbPL/MI7FDGeAdGUD/AgjawIEXD/HTlMMulbI=,tag:oRnWcmkT/7vxjK6nW0la1g==,type:str]
    password: ENC[AES256_GCM,data:lj4PzMlJM2VlzbSuqczaeTwCaHrcX8H595wSKPxJoXO7O/fx,iv:njkLSWO0G2/kZM2+xVSjEi/bRgy/MY8gpn+hYheh1Sg=,tag:+eZVs1qUsktcoyhlaoxvDw==,type:str]
sops:
    age:
        - recipient: age1svstfr65yepsdhxu3kxdy6t02gf6l779qxsqvd0dv2r0aqgzcpyqkwvl0c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1ZERoSmxhQ2pvam5TeFVw
            ZHBsc2JwaHJROW1uci83bGpMb2JSaWg0MzJNCmx4cmYwaHJvR1V3aHpJUXB0OThY
            ZlZLc1UwK3FKMEd6eFJBOFNGZDZicncKLS0tICt4TkpOSGtDSFJ0aWFkK0d1ZFFz
            eWhiZjRZbTJSeXBlWHRTb3dxUEI4Y1kKbt/KBPBMAQoHJuN7cxb1K2MXDoBL/pHC
            shh/6goXYMiATHk3VJKUWm07g0udD5OSv5V/QhhYcfZ2ia2CwQ1cbw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-04T12:32:36Z"
    mac: ENC[AES256_GCM,data:QmmlAYR/u2dM6hMierxnBa9xvse/yyi5638TshRIJbkWeOG3ehaDJcVISC+UI78O+cB7s7uMdnm6Ci/wEMcQsKfKl6rKJfY79NjQInMmvP1u4CzIV0xPdZ9GZKQSs655pZriCMN3ZXKiE3WZKxU55/0XtFvbQf0S8m9xoxypwHQ=,iv:L7w+SCPD5/az5q4qcrIUnjUyZ31LdLDJGL9UkeOwObw=,tag:i1R/rvdXgM6crLIIinpz7A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
