apiVersion: apps/v1
kind: Deployment
metadata:
  name: forgejo-runner
  namespace: forge
spec:
  template:
    spec:
      containers:
        - name: forgejo-runner
          volumeMounts:
            - name: runner-secret
              mountPath: /etc/runner-secret
              readOnly: true
      volumes:
        - name: runner-data
          emptyDir: null
          persistentVolumeClaim:
            claimName: forgejo-runner-data-pvc
        - name: runner-secret
          secret:
            secretName: runner-secret
