apiVersion: apps/v1
kind: Deployment
metadata:
  name: forgejo-runner
  namespace: forge
spec:
  template:
    spec:
      initContainers:
        - name: register-runner
          image: code.forgejo.org/forgejo/runner:12.8.0@sha256:c1d8edf7ed81119152ee4d9ff750ba3c2eb250cad0803c5ddea8c36078824c11
          command:
            - sh
            - -c
            - |
              if [ ! -f /data/.runner ]; then
                forgejo-runner create-runner-file \
                  --instance https://forge.superkooka.com \
                  --secret "$RUNNER_SECRET" \
                  --output /data/.runner
              else
                echo "Runner already registered."
              fi
          env:
            - name: RUNNER_SECRET
              valueFrom:
                secretKeyRef:
                  name: runner-secret
                  key: token
          volumeMounts:
            - name: runner-data
              mountPath: /data
      volumes:
        - name: runner-data
          persistentVolumeClaim:
            claimName: forgejo-runner-data-pvc
        - name: runner-secret
          secret:
            secretName: runner-secret
