apiVersion: ENC[AES256_GCM,data:bM4=,iv:VsisbXuUGNQiJPxexP+EMTLmr6SZhNYEK9gzIwJ4lJk=,tag:wMQFZ3Ci8iWtn3WDJdrNyw==,type:str]
kind: ENC[AES256_GCM,data:L7GFlBOI,iv:tXiImRxbd82YML/1gi9NdBWlPSepVxPvoHETmmdekC8=,tag:1t396dj7APYOvECJnnfcsw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:Dbu/DOiR8wXKgrfIkQ==,iv:sdwtPl7Oy105RsELt1gh5o04Y64A9ESFuWZhRvUFumg=,tag:9tEM92KbwoeO3lg41VvjXw==,type:str]
    namespace: ENC[AES256_GCM,data:tAOPyxA=,iv:K/PRwfSuXImsqJOfsmUTucVcbzk+bOLSczvZ1z+TEv8=,tag:zqfAVDpYV21dZSkhl/U++g==,type:str]
type: ENC[AES256_GCM,data:oWchPt0w,iv:CbvTfduhylAXLfnRPj9lFmklg4hAkI6km1CPMUrjDkU=,tag:o0Ngn+FrIR2rk3N6XHBlBQ==,type:str]
data:
    .token: ENC[AES256_GCM,data:ha6Rj/kTcxgcaGQwyUjh4yB/6YjWV1NFL5elmuIWGqCqk2VgzDY+bdiI2CrvRX6HTZLoyVPvsI0=,iv:ZHjMq+x8gah8RNwMMipGR1mqMYOwOx2yFNSQrXTk+O0=,tag:v6hei6gtQH5Wcrc3PKRtLQ==,type:str]
sops:
    age:
        - recipient: age1svstfr65yepsdhxu3kxdy6t02gf6l779qxsqvd0dv2r0aqgzcpyqkwvl0c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6d0V2Rmp2UythV2hxTHJJ
            eUovL2FVbXpXZlEwSTY3cjNZaU1XRmhWNEZnCjJkcUJod0NvWHkyRWlIVHNocFF2
            a01sZkE2SXJ6cmpaeGxrSHNiQTRsMG8KLS0tIFpsZTErWVdIVUVDNXZ4LzFLaGRS
            NnAwVndVc2RLUmpXVmVacWNsMi9PREUK8qifgpr1O0m1rVIth78ds3tktQ1W23oF
            SSvOcYgXIWrbxotCL8Th/gWKuo4/AxMdcmMN68UKAzXJ/WrrV+DnlQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-03T23:27:43Z"
    mac: ENC[AES256_GCM,data:s9n3lpknPFQy16nqF3jneKVYx3IgDNOmuoE7PdOtnRS7rZmfiQAa/b4beGm3ZghRQW+ESWxeWOMfaAmBbFxFnb4p1r6KZYRohSwQpWlXNlpIGbxQCu+FaYakkIhsDtA5Ibg6nH6/D6wlJZvRqktAf3IvataLIHP34VowTkGMOPk=,iv:Kau7RWTDZIW0jpTj64i1b9Ja2z1WEqNJfniB4ZUlEmA=,tag:FI6CqL/hgyC7r4nW4R/ejQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
