apiVersion: ENC[AES256_GCM,data:5Gs=,iv:lpFc+QIXgCXUusCv2O69Rll7HojjBFmUrG0/a2NKJEU=,tag:RBDhRP/6W2ZrBB7fLGwP3Q==,type:str]
kind: ENC[AES256_GCM,data:56UbqeSY,iv:u0AMMCV6PAN8ROuvYR33ENHFSNbd44+AkQ+SDoRTj88=,tag:IEtfYEEF+B/Eo0SxhVaCeQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:g6Mh6/iZlIpeRypJ0w==,iv:pb0+QnEjqhCxaKvEd7lq7ahgorDyRf7pTzxW+7T+sLw=,tag:JW4JQ0sdVvfdToZ/semDzw==,type:str]
    namespace: ENC[AES256_GCM,data:PUkHOVA=,iv:VO3yuyTJJcF1iXUSnT7ao3kiglU9UEJMquoQFN99lac=,tag:WcVpU6EvXNnlNZtrQhp4jg==,type:str]
type: ENC[AES256_GCM,data:USb3X3mY,iv:UFELA4q04I7L2v5HG95q5SFYpSsePxfm6nN6790rQnY=,tag:AdSE2a5S72ZYliEXiZAPRg==,type:str]
stringData:
    token: ENC[AES256_GCM,data:Q54yUUKRm8g+h1NuAMMR0bK3ZVOZmnFtr73AQo4CtuLWPl+CeXtSGwydVQ==,iv:YSDo1pPZ/SzKf0XLgXYotShwgLwoOVWNA5tQsmj0B9k=,tag:euFFLqabDtfmA5SiTJJ9nw==,type:str]
sops:
    age:
        - recipient: age1svstfr65yepsdhxu3kxdy6t02gf6l779qxsqvd0dv2r0aqgzcpyqkwvl0c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkVFVOWExCUDFaZ0pLMWxJ
            dDF2b1QzNTFsSDRoRjVsU09oWUppSFhRWWlNCktEQVJ4bTQwa3RKT1YweDdmY2p2
            aEx2aFFXZEJnKzJaOFBpdG1QRnVoaGcKLS0tIEt1ZERMQVQ3Y2tudkQzQXVmSzdn
            V2dtRmdSVGxEL3BGcHVwaVlDWHFLZFUK8FinqxZ29hISlMBvq6oQJe7GCAQur7eK
            v7EDY2iSkcjiBAOAOnJCsdRtuHWp9PMqgruWRKW4DE6sSG/la9oebg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-02T19:28:36Z"
    mac: ENC[AES256_GCM,data:qNPFYm5Es0WTnQFxn2oWWSh+gQAyE0CJiC+e31zXw+C+OBrPR9iITeTxDIz5Xm9Q0ahblqnkpoUfyzCOTEPeI45RuW7uikY8qDv3vWoiWfNIJIH1XNHEsnPv5L6mAYhJr0TQWB0a0wZUdYGDGgilB5nwXMV9lCWRGOktVslvKaU=,iv:RE5Kx3gNunqvSi0uNHoiaG2b7lrpLDb2dnyJNZdNIOM=,tag:rbQQ+tlQWScl6IEgE+uClg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
