apiVersion: ENC[AES256_GCM,data:dnU=,iv:pfQz98r4FlZmRJcllGbgsYsO5wcTLk8a85NphE9eS1Y=,tag:6rNFK7snmCut2HXZw1hWrQ==,type:str]
kind: ENC[AES256_GCM,data:b47ZQ1/H,iv:L9K8j7LtKYu9oIMmBRXClj4JmsKwivCW/S3RS4bRf0E=,tag:JeLnIaVdIjnoK3nfbeHcVg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:Ivd05mhZ7HlmSzwfOw==,iv:0xK2hnyaOTSSkJX+hmuj0VS7xHMsJYBWeEm1qMSPQ8M=,tag:P6WeUVJoQDFhnkhT18pRVA==,type:str]
    namespace: ENC[AES256_GCM,data:kaFTq1g=,iv:62spQIWh4yMjrs7hk+mcyIXMdeXuhOQsfsX/YhIuzKU=,tag:IzavYps9dwDxrA3CzYff2g==,type:str]
type: ENC[AES256_GCM,data:PDFZ3Jdq,iv:x8B6d+iPVoRRCAoqNXoxqIenYzcfhDWSDt2F18alMx0=,tag:Xl7gwQuuah9K1jzSHPpiTg==,type:str]
data:
    .token: ENC[AES256_GCM,data:+dz5JdHofIhqNDPkpC5X8tIbPU8A6JgA33nVdO5/wlKZpmTKAPgMlHr3kIMCd1z4Cw/57wGTPFs=,iv:37eu3Q8A/Ynu2RgnX+eq3phdZraJDDhd9caGKjaJX6M=,tag:FFCcMhwGELzihCYx9KMm6g==,type:str]
sops:
    age:
        - recipient: age1svstfr65yepsdhxu3kxdy6t02gf6l779qxsqvd0dv2r0aqgzcpyqkwvl0c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLNkd4UGpwYmVZbVNTVGgy
            NHNkT01GQUVPVDl2d21wM1d0b3lzZTIzemlNCmo3Y3FDZ3hwNXhaTnc0WXJJV0Nw
            c29JbGQ2Ym82SEYzOXozUlpIUElNV0kKLS0tIG5KQ1NsTnlHUlZDWCt2bFhZSVJo
            WmRIV1BsYXc4V3YvK3VrOFVVVlVLSWsKJECk5JYAsgN9rh6pvSSj7aX7C7OHjS4T
            3PCuqKKB6Cy51zzGOjf3YX0BbiAZkHAFFHL1mUq65R2NKClbgD9cWA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-04T10:49:14Z"
    mac: ENC[AES256_GCM,data:XWrUpzWGacV3Ic0nbrp+yoXYlu/rZiRS0Lajf3DuOJojm3YAcTwYeu8DoHWRMqgx3OyhDlGgdyZ+Pgl+RDnQZQutIqo/HgzqBZ+Uu4kUWF0YPzm1dzaTSJzWviW9L//IdaH4k4g2yX8cOY83GzM0uJVdRQhpzRuRa1jPhufHcqo=,iv:tIB723V1MiNHBTZ//Ec/mJNpIbDTXdz5BPWWE6P+UCU=,tag:GTXjJzREO6nzgv7raAkEOw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
