apiVersion: apps/v1
kind: Deployment
metadata:
  name: discord-quote-bot
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discord-quote-bot
  template:
    metadata:
      labels:
        app: discord-quote-bot
    spec:
      initContainers:
        - name: migrate
          image: forge.superkooka.com/superkooka/discord-quote-bot:1.0.0@sha256:a1884b7815c3e3bfb0b3049ccd5b60abe4a9e70a06e9c5208763b993d4f0c201
          command:
            - /usr/local/bin/migrate
            - up
          env:
            - name: TZ
              value: "UTC"
      containers:
        - name: discord-quote-bot
          image: forge.superkooka.com/superkooka/discord-quote-bot:1.0.0@sha256:a1884b7815c3e3bfb0b3049ccd5b60abe4a9e70a06e9c5208763b993d4f0c201

          env:
            - name: TZ
              value: "UTC"

          ports:
            - containerPort: 9000
              name: interaction-api
