apiVersion: apps/v1
kind: Deployment
metadata:
  name: discord-quote-bot
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discord-quote-bot
  template:
    metadata:
      labels:
        app: discord-quote-bot
    spec:
      initContainers:
        - name: migrate
          image: forge.superkooka.com/superkooka/discord-quote-bot:dirty-latest@sha256:1fbc11f4d521e1f630e0c07d429e6394d6c0881b12afa01f14c0e330ea721834
          command:
            - /usr/local/bin/migrate
            - up
          env:
            - name: TZ
              value: "UTC"
      containers:
        - name: discord-quote-bot
          image: forge.superkooka.com/superkooka/discord-quote-bot:dirty-latest@sha256:1fbc11f4d521e1f630e0c07d429e6394d6c0881b12afa01f14c0e330ea721834

          env:
            - name: TZ
              value: "UTC"

          ports:
            - containerPort: 9000
              name: interaction-api
