apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - traefik-helmchart-config.yaml
  - traefik-login-secret.yaml
  - traefik-certificate.yaml
  - traefik-middleware.yaml
  - traefik-ingressroute.yaml
