apiVersion: ENC[AES256_GCM,data:xRY=,iv:WAPoM4xCGVEmhbe1avCqhPt4Qr4RDf0AjT3O2JcvzEQ=,tag:2SvkOCW0wTSYpGvGM7UoUg==,type:str]
kind: ENC[AES256_GCM,data:x8TzeILH,iv:uXM/dtADPg00KncCxM63a10R42sqaaKCWnDC7gnCM/M=,tag:5foouEV8B2Tk1DFQEbI7vQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:G2qA++4LMTRI7/1NhmBdHYs=,iv:dUOfPoKGAVIsKk15lQQfdWiddGG3U7ISsfZ89GUQeCQ=,tag:JQ++thfd8SIqT1UK9uiq3Q==,type:str]
    namespace: ENC[AES256_GCM,data:5b75PC8xLDdyLjQ=,iv:cNfAh/n9LYUTYWWzUs9KgrGfB7s4xR+CegshXji4rFI=,tag:eONBc+xtaCVpXOgwBS0KTw==,type:str]
type: ENC[AES256_GCM,data:ucaAdss9,iv:JVljOATiWxXlgQ7scfyU4NXhp9F0dMrKSxIfDrPYHa4=,tag:fMxGWX2LP4trCpCnyocb0A==,type:str]
data:
    users: ENC[AES256_GCM,data:UmNWvUhSD7ta1/akuvTm9o2/fhcCigiD5g1NhHlB7nXuA+wKqApPnDoh2cePXLwbKh18Qfs/ixkLINBl,iv:5yjF+Or1NwyAg7YPz7JZ1JGT3YBIJQBlXfAG2FQesn0=,tag:Bv0hauDSSZy/TG2KnBv6hw==,type:str]
sops:
    age:
        - recipient: age1svstfr65yepsdhxu3kxdy6t02gf6l779qxsqvd0dv2r0aqgzcpyqkwvl0c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyZkRiaEx3NnJQMktOaUF6
            UXUvUi8vM3ROOXVDbmx3WXBSajJIYng2M21VCmRkNFI2bDZocTBhQ2RBVHM1SVZ0
            RTc2UDB6SmZBTGhYRlQzYThJaU5mb28KLS0tIGJzR09nR2NSclZ0QjBBWm4zS2o5
            bXFOZXltSTVCVjcwcnJJeERIMk5zRnMKQ/mdFcVDPEpe19xTrExpd+Hg6po7cGd7
            zGgMalFeJ8RQJ6cg7b8Uj5GJFuaVRWotr31NrBRr6mDLK5a3zQG9ug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-10T02:33:27Z"
    mac: ENC[AES256_GCM,data:DtRNlLXAWvWTYFU5Q1fNXSU+3kk1YTuVAtobe56izgo8wVPf+2+6vTyKNNH8qUR9jmKDAmccusLtD+AJaC/lAcX6JmLAJ0UUmlrxBClm2jLYpnq2FO81D5Oz6ymHBP8n7W1IkYwMGBS9v182qE6442cZqNmwfcuoEupAUwUSCLA=,iv:yls4D5oWqJWQjszTRzfAZRI+/mG1l8PNME3X/yxilUU=,tag:1g6wDobHrXCcZmZYPn6VBQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
