apiVersion: ENC[AES256_GCM,data:kys=,iv:bc4zs1pQ1ewIBGRNoMqWunkc2p/NGRiiUhrkaV8S0bc=,tag:3okafbB1hvR0MW3ipbfSUw==,type:str]
kind: ENC[AES256_GCM,data:WktsRV3L,iv:IO3zhN1+Zq0sgpJ+1af663WklmrIPSqEXAbJpyqCyyA=,tag:Qg2zPCdo7Rnz6Y6dTz/pVQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:okG2D4s0c3N0uqirtS79viI=,iv:/BKH5UJsTRTvlJ/uAsm+BsXa8hUgeOgj5ZpAzii9whc=,tag:lGFSZ9Evkl3CbwAgRRBW7g==,type:str]
    namespace: ENC[AES256_GCM,data:kqs0A8RIoq7uK7OVtu4=,iv:HjwysnFErJ0MKXul6N/wzlqMxYqWsNz9rRIAWIUSrms=,tag:PNNmEUqF+L6uvHMsLMUw6w==,type:str]
type: ENC[AES256_GCM,data:8SBTfnRi,iv:GtamXHWgNcnGw7RFdZb8IUta/jcJoJG4fGmitSMEsnc=,tag:XZ4fFTw9w3m7VjKR2+vqeA==,type:str]
data:
    users: ENC[AES256_GCM,data:Xk7OPWtuymTZwRyOl0JAnzYDJKEPDyqylVIHOToDuHOSAJvz8DtZjvB/NzGTz4wIFqg83EuggxWtGp0a,iv:YEadLxptBnoxBAJJTCmao3/ODTlDYwxTyCBlXhVO3FA=,tag:TPqgwAhf+0Zvx78iMgXUKQ==,type:str]
sops:
    age:
        - recipient: age1svstfr65yepsdhxu3kxdy6t02gf6l779qxsqvd0dv2r0aqgzcpyqkwvl0c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBURzZvMHlyY0pYeWYvS0NX
            d3hMR1BscllBVHlUYng3Q3V1aDhsSHZJTGlBCmFYbWUram5BL2VUMUgrbThYNm1H
            bmpTQmFWNlNqTTZrRmtDSWtMMm5ZZ28KLS0tIEJQVmlGM2pVajVEK0Nyb0M3WFFL
            TEFpajVZcWZ3anVrR3Y5cjNJNVhOSEkKH3MdYVgUfZzOfXtpZ/L3PpGAr0NSIOfB
            MO1ewblfWhRjb7PicePqPoZjszpt6EW7wS2BJP8bc3gK2MYcV4ZNEg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-10T02:30:05Z"
    mac: ENC[AES256_GCM,data:IaEmWuO/FqYYfLWPVzUOoXL/U6YtN4amWvMmiyR7mz5MQdKq+2sjWKsx2nR9Sxek0ThHA1yame4awFIkUNhExrFIrPrseGK2zd2JvoDRI9UQTzuYK7iTpqnLkpw1jFFZ6foTwrZ4P3HyX1t40JPwzHLwi0EOQ9a7l/quDV8Nf6g=,iv:rMXahaUv18uufrgql/3pJXGvIEoD76wOin6GFw/JVN0=,tag:Edg3SVsAmcKwJY/gIrklgQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
