apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    api:
      basePath: /traefik

    service:
      spec:
        externalTrafficPolicy: Local

    ports:
      sftp:
        port: 2022
        expose:
          default: true
        exposedPort: 2022
        protocol: TCP

    ingressRoute:
      dashboard:
        enabled: false
