apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    experimental:
      http3:
        enabled: true

    ports:
      websecure:
        http3:
          enabled: true
        advertisedPort: 443

    service:
      additionalServices:
        - name: traefik-udp
          type: LoadBalancer
          ports:
            - name: websecure-udp
              port: 443
              protocol: UDP
              targetPort: 8443

    api:
      basePath: /traefik

    ingressRoute:
      dashboard:
        enabled: false
