apiVersion: ENC[AES256_GCM,data:1vQ=,iv:TjBR5GEfnYaFWYAol0o6mncg4aco4okJOQr0BvR9DmA=,tag:Z0j8HpbndhP1dlR4aubcKw==,type:str]
kind: ENC[AES256_GCM,data:6iZS5Prm,iv:BVzjoV/6BAteS9M7cXPhFKH8eL6D4RAvdsLm+pa1ai8=,tag:a6RlVbR480SX8+RJLCzyUA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:j7I3VkfIh6pferGyKwDKO+I=,iv:oqO5yuDu9SEfs61QpPRLRlpzB3bd8B2yM9wCxC6yE14=,tag:GzVopWklQTLQdNCK8erMlg==,type:str]
    namespace: ENC[AES256_GCM,data:CRAHxSNDlg==,iv:mF3+K+pLje5lHeroIQvXmZBXX8sb4oVF3RIutGDs+M0=,tag:VEx6yTdsVXKpMarSlcb4UQ==,type:str]
type: ENC[AES256_GCM,data:uOoZ6atb,iv:OMy9TaXCkWkiNxKB29uMr2F+HA7UYAL+s0KZa8z/YuY=,tag:VXvT/Q/u3nOnTEKBKab5oQ==,type:str]
data:
    users: ENC[AES256_GCM,data:h6JKQXqh6e1PZ9l3cCvNi6Pfh+MNgLhrlFiyV7C/im8UMC6hV+rdxX0gGkOkcLD96cWRd916Fiza15Tf,iv:TrEQ928drA+9kLBvkoxghriFwdjV/TQ3NCtECf5LY+w=,tag:2Wy5/vKWfngg9F1RGsN/Xw==,type:str]
sops:
    age:
        - recipient: age1svstfr65yepsdhxu3kxdy6t02gf6l779qxsqvd0dv2r0aqgzcpyqkwvl0c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6Y1dFZFU0ZDlIczFaK1lT
            dzkxdmlWMmhyVWFHYkxkeHh1R3RMQ1BOZzFBCmtkZzdOandWV3RGSnc0dWNIMmN5
            MFFCSjA4cWFpU0xJeExzVFNTNnpqUHMKLS0tIGp2TVBmc2dzUXBlVS85L3VRVWZJ
            ZnhSaVYyRUFpV0h1b2E0bFVVYjBNbjgKTFIl6kcLIaAtQOFkN/bFEdkWne1/B8xF
            IbNkwurfYeXRCZmfXULPL0cz4wca0e3MiZkvxEhs67tpf3uCu/RJyQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-10T02:21:43Z"
    mac: ENC[AES256_GCM,data:RkBcFvXDMM9Id0/pC8B4wl1bi4cKi4ds4l5CotfPT03WW5pxZtD7wxrCFGFJWgBFIrLS168Z92XMBnWR95KWEIYQ54I5Mnf/eHmVazSN1+0VzTknzrfx6K4N5ZkUcOQso7wByJ42KHK3ld4n4apNKtcfzwxZGrHe5Yn9segZPVI=,iv:9W7FEpLeybsOtNn6WsoqUs1cyIcAZgo0TlA3WTmEqOk=,tag:wQpEkPEg8yPDtkue71zGAw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
