apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    api:
      basePath: /traefik
    ingressRoute:
      dashboard:
        enabled: false