apiVersion: ENC[AES256_GCM,data:znc=,iv:LxIVThYZYdBz2rhuTKMu13pN3ck94yL+JYgy2ry3xfQ=,tag:tjKTcqszMVSg6l82ynss7A==,type:str]
kind: ENC[AES256_GCM,data:yz6ta5vy,iv:WbDiWy+nLJHymK5PtLevA2ZMLZzn5IfIhR5WoOiaMr0=,tag:43i1VYH851ty4644fVY7bw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:OTpgWEq0eQpCbJJFMU98b2oN,iv:VS9VfDEj7z+IbwFDTcHtxGr6JcZodIhAwTQojnjBtn8=,tag:aVj/2t8Q2TOI76jRkVNYhw==,type:str]
    namespace: ENC[AES256_GCM,data:dcKntb0=,iv:4naz67yn9V8S0eYPcbLW0Z+vdamboqYIcxA8kMrH4/E=,tag:/sHjTtGIsKPMzKANKK++Qw==,type:str]
type: ENC[AES256_GCM,data:10h4nCSP,iv:jd1Scvfvzz+MQbe36CTQic9K8llbitDypFCHqJg2gWU=,tag:+dsgIkArDz3enkzPRtvgZQ==,type:str]
stringData:
    username: ENC[AES256_GCM,data:Bq23WIQ=,iv:tNCcEzGymqYCd84hG2yBCqF8n9sM7Y4CM8MoKwlOcOs=,tag:SENuAoEFpWGGJq8UuUzeBw==,type:str]
    password: ENC[AES256_GCM,data:a6VkzgiqOtpej1hP9kvxw3pKa33wTE4pBn2IOkw=,iv:CuiIVzcRDbR5Gx1yqXAbzM+/8lIkILVuFSHUq07gvpA=,tag:toQxGZiQ/DHl6+O+6ZIV1w==,type:str]
    email: ENC[AES256_GCM,data:9EaFrxQqdYQH/5ldKoYfa/AqGPs=,iv:UGBhsgg0rx+R8XMPf7QhK9d6qy1lkOG/KLb7PDOME9U=,tag:s4ws7bN6uD/9oJmORuk1KA==,type:str]
sops:
    age:
        - recipient: age1svstfr65yepsdhxu3kxdy6t02gf6l779qxsqvd0dv2r0aqgzcpyqkwvl0c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0Mm96eENVeStMaTlzQkJa
            bHFSTkFQdnFzQ0x5TGZCYnZuZHpiMm92cm1JCkowRjY5Z3VIV1hYcFBGbFFBVWpR
            QjlFbFhSRWdqZFp2VnRvMjJLVXNwQjgKLS0tIDUwRW5OMTJQM08zcW1WZnAvdmdP
            dzdwZlEwV3lRVkowaTRLUGpPbVdVTDgKfwIGDrxs7f4t4bzvyVfWOdODn9JxDsvc
            EXg/PTiMbwXtKbXU+wkbEYnZz1sKBPxC5Lt61EgVhsz4auZJ76UDCg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-04T19:13:18Z"
    mac: ENC[AES256_GCM,data:XL5+1d9aM7EhrAbSDyC1T7vAVl4RZmqyqy+oXY3qkhqre6ZtSE3iRngY/JnE5EOGCY7eykBks/KNTYebW1KTsRRoNSYWvVvMD9cMsjc3kAAQjliSnTDRuYRzCTHVRU09fSGz47r7lZXzGvChJeo7pqlk3XtRv7wtVzVAaf5Jm+I=,iv:vD506FNPwf61Sei+Pos8LnLZlt7265d7jH3dK/51+vE=,tag:Ktl4yX3IINa5AeF3VR83Tw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
