apiVersion: apps/v1
kind: Deployment
metadata:
  name: blocky
  namespace: network
spec:
  template:
    spec:
      containers:
        - name: blocky
          args:
            - --config
            - /app/config.yml
          volumeMounts:
            - name: config
              mountPath: /app/config.yml
              subPath: config.yml
              readOnly: true
            - name: tmp
              mountPath: /tmp
          resources:
            requests:
              cpu: 20m
              memory: 32Mi
            limits:
              memory: 128Mi
      volumes:
        - name: config
          configMap:
            name: blocky-config
        - name: tmp
          emptyDir: {}
