apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: blocky
  namespace: network
spec:
  selector:
    matchLabels:
      app: blocky
  podMetricsEndpoints:
    - port: http
      path: /metrics
