apiVersion: apps/v1
kind: Deployment
metadata:
  name: pelican-panel
  namespace: game
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pelican-panel
  template:
    metadata:
      labels:
        app: pelican-panel
    spec:
      securityContext:
        runAsUser: 82
        runAsGroup: 82
        fsGroup: 82

      containers:
        - name: pelican
          image: ghcr.io/pelican-dev/panel:v1.0.0-beta33@sha256:871032c289b7e00a23e1eb701772603750a14b8c7cfa72b072058ce645c41032
          env:
            - name: APP_DEBUG
              value: "true"
            - name: BEHIND_PROXY
              value: "true"
            - name: TRUSTED_PROXY
              value: "10.42.0.0/16,192.168.0.11,127.0.0.1,172.16.0.0/12,*,**" # at least one should work
          ports:
            - containerPort: 80
              name: http
          livenessProbe:
            httpGet:
              path: /up
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /up
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          volumeMounts:
            - name: caddy-config
              mountPath: /etc/caddy/Caddyfile
              subPath: Caddyfile
      volumes:
        - name: caddy-config
          configMap:
            name: pelican-panel-caddy
