apiVersion: apps/v1
kind: Deployment
metadata:
  name: pelican-panel
  namespace: game
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pelican-panel
  template:
    metadata:
      labels:
        app: pelican-panel
    spec:
      securityContext:
        fsGroup: 33

      containers:
        - name: pelican
          image: ghcr.io/pelican-dev/panel:v1.0.0-beta33@sha256:871032c289b7e00a23e1eb701772603750a14b8c7cfa72b072058ce645c41032
          env:
            - name: BEHIND_PROXY
              value: "true"
          ports:
            - containerPort: 80
              name: http
