apiVersion: apps/v1
kind: Deployment
metadata:
  name: personal-forgejo-runner
  namespace: forge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: personal-forgejo-runner
  template:
    metadata:
      labels:
        app: personal-forgejo-runner
    spec:
      containers:
        - name: personal-forgejo-runner
          image: code.forgejo.org/forgejo/runner:13.0.0@sha256:7fb853bfe73c229be6349398359c0a7bd01fadfd17c106607b2221150b799ed2
          imagePullPolicy: IfNotPresent
          command:
            - "sh"
            - "-c"
            - |
              while ! nc -z 127.0.0.1 2376 </dev/null; do
                echo 'waiting for docker daemon...';
                sleep 5;
              done
              /bin/forgejo-runner --config /etc/runner/config.yaml daemon
          env:
            - name: DOCKER_HOST
              value: tcp://127.0.0.1:2376
            - name: DOCKER_CERT_PATH
              value: /certs/client
            - name: DOCKER_TLS_VERIFY
              value: "1"
          volumeMounts:
            - name: runner-configfile
              mountPath: /etc/runner
            - name: docker-certs
              mountPath: /certs
            - name: runner-secret
              mountPath: /etc/runner-secret
              readOnly: true

        - name: dind
          image: docker.io/docker:29.7.2-dind@sha256:12e683a161823b2a839aeea999b9d960e6e1f9a97b1679ad6b441982e2d9cf07
          imagePullPolicy: IfNotPresent
          env:
            - name: DOCKER_TLS_CERTDIR
              value: /certs

          volumeMounts:
            - name: docker-certs
              mountPath: /certs
          securityContext:
            privileged: true


      volumes:
        - name: docker-certs
          emptyDir: {}
        - name: runner-configfile
          configMap:
            name: personal-runner-configmap
        - name: runner-secret
          secret:
            secretName: personal-runner-secret
