apiVersion: ENC[AES256_GCM,data:Ntw=,iv:ecpc5hoYK8n9to/JI8YjixFKg4uEB39Qhb3klVLbP4M=,tag:6BTQUNmRiVszjJrWxIGOmQ==,type:str]
kind: ENC[AES256_GCM,data:MF3JwXS4,iv:m6Qlvb2gG+YXSPx9Wxf+gypI+cwmyh0m/QQiBotkqCQ=,tag:zueuOJYrjq6Ig/wTbVEEUA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:J3MIXCL7t1MFpH5F6j/7UoeSJ9bQBA==,iv:PU3Xh4zh30lx3pScDaR9TXXLGTZB4EylzHtExCqqvNc=,tag:nuavWGMfLsGNuSJ4uo1MOQ==,type:str]
    namespace: ENC[AES256_GCM,data:NMULI0Q=,iv:YO13lfQZ9XiByZvTBdfAm6yN4fC69WIOgQX9YA3Ftps=,tag:nfCPvuIHWdKIasuw+ThaoQ==,type:str]
type: ENC[AES256_GCM,data:HYvQnBLe,iv:lwRplfVUyTSuYPhMullX0N37h28HGFuAM+6jmtDdmnw=,tag:sEnPHmgNgiK026q1YuiIRw==,type:str]
data:
    .token: ENC[AES256_GCM,data:QRs/W2X83pvewYCNkAM4tIni0TYn91IzT6g1LpEOyHiDLt4aF6uxpYMu6IqzBCfLmOnQdAlBGRg=,iv:IrRfyi4B3Q6gSVvZlpxhVrsrZOvoHPj8HaEvExiGFFU=,tag:x74j4S3tYs0Y6s/im43s1Q==,type:str]
sops:
    age:
        - recipient: age1svstfr65yepsdhxu3kxdy6t02gf6l779qxsqvd0dv2r0aqgzcpyqkwvl0c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2dHVTK0ovL0FKZGpZYldC
            NFMxcHhWWXdGamVjN05oMmtVN1UrMXEvY1dFCmFrbXorY2QyL2xtKzNJSkF6TzVJ
            cUxCT3IrYVpxOWp4OFhhZ1JScFc3OGcKLS0tIDlHM3RzeFZFLzd4Z01CeEdKR2tX
            QWVadC9MY3FTcjZwV2VyZG5pLzVva1EKSv1VhBd+Y2PM0OhB/oelcq5ctGU0NSNW
            vCbm2vWG8Lz9XjbLbfCv1bcz4GYolV3GSS7qwj+ul2p9n545TNcgBw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-22T19:50:42Z"
    mac: ENC[AES256_GCM,data:eTYd+m1WEeMVe8bP+9fkN6duspxqPcpDSQri54i0yir5CEsPRJNAlD/Zy+eXBxQQAfvjot7SbKw5zIdGHs4vEY7fhvH3Q/3+JOKUjIM7v3u+Ae5Ll6VQNUSbazFLFn3oL7nqO4TKV0tPEdYejLmkOBOe+kMpvJEbw7ZXXYdvEcg=,iv:7cPdvS8AQUPEcGw8l9QOOv1h81beBAqpZLgOln41FV0=,tag:EvCu5RmYWnzpGGD9leh/5Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
